In [10]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import json
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
from itertools import combinations


# allow dataframes to show all columns
pd.set_option('display.max_columns', None)

In [11]:
df = pd.read_csv("ramp_downhill.csv")
df.head()

,id,file,side,step_length,stride_length,speed,gc_dur,stance,cadence,hs1_sec,hs2_sec,to_sec,start_frame,hs1_frame,hs2_frame,to_frame,slope,condition,height,weight,age
0,11,11_1F_2,Left,0.653310,1.278924,1.117940,1.144,0.597902,102.671668,0.132,1.276,0.816,31,33,319,204,-18,self-selected,180.0,76.0,23
1,11,11_1F_2,Right,0.575531,1.228806,1.089367,1.128,0.613475,113.568087,0.688,1.816,1.380,31,172,454,345,-18,self-selected,180.0,76.0,23
2,11,11_1K_3,Left,0.698530,1.338955,1.170415,1.144,0.597902,100.532497,0.096,1.240,0.780,22,24,310,195,-18,constant,180.0,76.0,23
3,11,11_1K_3,Right,0.699632,1.398149,1.184872,1.180,0.593220,101.613868,0.660,1.840,1.360,22,165,460,340,-18,constant,180.0,76.0,23
4,11,11_2F_1,Left,0.685120,1.303506,1.104666,1.180,0.583051,96.742068,0.136,1.316,0.824,32,34,329,206,-12,self-selected,180.0,76.0,23

In [12]:
with open("MuscleJointForces_downhill.json", "r") as f:
    data = json.load(f)

In [13]:
df_all = pd.json_normalize(data)
df_all.columns = df_all.columns.str.replace(r"^results\.", "", regex=True)
df_all.head()

,file,side,GRF_ap,GRF_ml,GRF_vert,angleHip,angleKnee,angleAnkle,momentHip,momentKnee,momentAnkle,ankleFres,kneeFres,hipFres,knee_PFc,gastrocnemius,soleus,tib_ant,quadriceps,iliopsoas,hamstrings,glut_max
0,11_1F_2,Left,"[14.754200319555064, 18.912309344826987, 22.98...","[-1.3715455322886239, -2.60016714213597, -4.14...","[88.49850114087053, 116.81301153744096, 147.77...","[23.11970903388696, 23.309768192680707, 23.523...","[7.580195073887036, 8.112639291594181, 8.70766...","[3.7678227120168204, 3.4415852315374624, 3.094...","[16.63287453541254, 24.065055010039178, 31.950...","[-13.857913524211412, -15.870451168632028, -17...","[-3.1485837547315914, -4.469778826614926, -6.0...","[394.68391495815433, 429.81289654858523, 465.1...","[560.0616124302376, 657.3946049910797, 781.935...","[752.1144931344963, 871.8762377814713, 1033.83...","[3.2380869044055294e-08, 1.1732621863216089e-0...","[84.96180226295617, 65.70585493023083, 41.6241...","[3.2943171191056034e-08, 1.1740339184142212e-0...","[176.38100095031484, 191.629313989953, 207.527...","[5.2125076463242117e-08, 1.864875651977497e-08...","[83.26766663728114, 77.17933833075641, 78.3861...","[362.22294477843997, 452.0210137914681, 566.13...","[8.925436591790988e-07, 5.083358806623616, 8.0..."
1,11_1F_2,Right,"[14.019394623448846, 16.54752373052943, 18.458...","[1.026029499850483, 0.8009821609932601, 0.4176...","[88.11956142717656, 116.47818235269114, 147.54...","[22.191209060403597, 22.304023552664418, 22.44...","[13.606344174955472, 14.189785189696607, 14.83...","[7.992639049878598, 7.822939112077673, 7.63622...","[11.106311173373069, 17.004631066661812, 22.80...","[-11.623237519464524, -12.310145563421122, -12...","[-2.282079067271943, -3.271463104128628, -4.46...","[350.8691773260563, 351.83055343164006, 361.57...","[455.7122531312876, 484.37806130501565, 547.12...","[653.886955140613, 716.5097673832856, 813.0375...","[5.407310987679742e-11, 6.307605881972114e-09,...","[66.11529269705329, 32.735130377895764, 1.9716...","[4.731476188140097e-11, 5.379522917968298e-09,...","[147.4796339677098, 142.40576806106415, 141.56...","[7.810866650057915e-11, 8.978042484973225e-09,...","[76.3778536331347, 60.5071284669632, 56.458943...","[280.65043795478795, 324.296768993416, 392.342...","[1.1576766825634846e-09, 8.676547692965617, 13..."
2,11_1K_3,Left,"[9.429961991945866, 9.340841983225303, 8.16930...","[3.4425211943193355, 2.9945048919933983, 2.143...","[138.7897836900715, 181.53336237781622, 228.28...","[17.895441689720638, 18.109463768161685, 18.34...","[8.239329335860647, 8.945025919863918, 9.70789...","[7.831656644416162, 7.478930850804061, 7.09810...","[22.78806326481839, 29.979831210441002, 36.983...","[-14.272388807133616, -15.018760259452398, -14...","[-3.6531354512311824, -5.549440673363604, -7.8...","[415.38235006751023, 433.7150073900413, 523.22...","[629.11461721485, 718.8791806478171, 782.29753...","[962.8397283823093, 1110.524774710165, 1171.09...","[9.187064184845183e-10, 5.697195572078916e-09,...","[56.88031077288465, 14.749651061901128, 2.6207...","[8.441105569970356e-10, 5.7496904985480135e-09...","[170.70999554436202, 176.86849796418878, 218.4...","[1.4435282659132238e-09, 8.838779138101165e-09...","[115.64974425205095, 107.75072707865156, 75.81...","[422.0605383766697, 511.4376776942769, 560.479...","[1.14037694938436e-07, 6.839783427937151, 25.6..."
3,11_1K_3,Right,"[10.386012932655106, 9.53512269567237, 7.37720...","[8.140293625764647, 9.286994267355297, 10.2706...","[119.94664003379371, 158.57531760916373, 201.5...","[19.49775808106458, 19.701253204733273, 19.924...","[12.787580373406977, 13.561564317995675, 14.38...","[7.713202485879993, 7.493746397505441, 7.25453...","[11.513682094495506, 16.452024076036235, 21.04...","[-7.5648508951440645, -6.66735122355985, -4.90...","[-5.306948473009778, -7.162172800051598, -9.28...","[349.7386666441944, 458.07854810015874, 578.35...","[327.6868901138671, 356.7855578396026, 355.358...","[642.8465310816695, 670.1796472142004, 735.247...","[8.949862627158693e-08, 3.548017698943229e-08,...","[8.815070347499736e-09, 3.783138353967775e-10,...","[2.085122014868046e-08, 1.503551917724428e-09,...","[155.56041457364057, 203.92736467240016, 257.9...","[1.292434829496956e-07, 5.061166359741332e-08,...","[67.01899230507159, 29.83849272580364, 28.0899...","[213.1643418453964, 225.72105302320838, 216.65...","[12.625349179022976, 34.51506472716318, 87.897..."
4,11_2F_1,Left,"[-9.098609966945734, -12.61885424034078, -17.1...","[3.374502538740886, 4.031375084438764, 4.75680...","[165.08840022807746, 216.61540960689774, 272.9...","[19.086138939557287, 19.24169854251254, 19.415...","[6.162202286513988, 6.797498973017147, 7.49154...","[10.805377739583259, 10.512222624897953, 10.19...","[22.772753336697935, 28.315300410374366, 34.09...","[-10.964380870586663, -10.572041100968157, -9....","[-7.9129651429129915, -10.690688381174994, -13...","[593.0051455932584, 755.6464710469252, 932.936...","[550.5134056289367, 623.686301092125, 670.2149...","[912.5990166906339, 1007.3015915373205, 1137.5...","[2.032527435378688e-09, 6.522308834697417e-09,...","[1.7360543670884385e-10, 2.453428019468688e-10...","[4.941368773179446e-10, 7.558865552899786e-10,...","[256.82688113454617, 333.12124654066383, 418.0...","[3.3277355464871163e-09, 1.0537415519334869e-0...","[27.057709547071784, 1.1235656961623449e-06, 4...","[370.50180202485757, 405.6411237966206, 423.21...","[42.59115724532714, 62.33986091359603, 122.452..."

In [14]:
df_all['angleHip_length'] = df_all['angleHip'].apply(len)
print(df_all[['file', 'side', 'angleHip_length']])

        file   side  angleHip_length
0    11_1F_2   Left              286
1    11_1F_2  Right              281
2    11_1K_3   Left              286
3    11_1K_3  Right              294
4    11_2F_1   Left              295
..       ...    ...              ...
363  25_2K_3  Right              258
364  15_4F_3   Left              267
365  15_4F_3  Right              269
366  15_4K_2   Left              317
367  15_4K_2  Right              309

[368 rows x 3 columns]

In [15]:
# merge data
df_merged = pd.merge(df_all, df, on=["file", "side"])
df_merged.head()

,file,side,GRF_ap,GRF_ml,GRF_vert,angleHip,angleKnee,angleAnkle,momentHip,momentKnee,momentAnkle,ankleFres,kneeFres,hipFres,knee_PFc,gastrocnemius,soleus,tib_ant,quadriceps,iliopsoas,hamstrings,glut_max,angleHip_length,id,step_length,stride_length,speed,gc_dur,stance,cadence,hs1_sec,hs2_sec,to_sec,start_frame,hs1_frame,hs2_frame,to_frame,slope,condition,height,weight,age
0,11_1F_2,Left,"[14.754200319555064, 18.912309344826987, 22.98...","[-1.3715455322886239, -2.60016714213597, -4.14...","[88.49850114087053, 116.81301153744096, 147.77...","[23.11970903388696, 23.309768192680707, 23.523...","[7.580195073887036, 8.112639291594181, 8.70766...","[3.7678227120168204, 3.4415852315374624, 3.094...","[16.63287453541254, 24.065055010039178, 31.950...","[-13.857913524211412, -15.870451168632028, -17...","[-3.1485837547315914, -4.469778826614926, -6.0...","[394.68391495815433, 429.81289654858523, 465.1...","[560.0616124302376, 657.3946049910797, 781.935...","[752.1144931344963, 871.8762377814713, 1033.83...","[3.2380869044055294e-08, 1.1732621863216089e-0...","[84.96180226295617, 65.70585493023083, 41.6241...","[3.2943171191056034e-08, 1.1740339184142212e-0...","[176.38100095031484, 191.629313989953, 207.527...","[5.2125076463242117e-08, 1.864875651977497e-08...","[83.26766663728114, 77.17933833075641, 78.3861...","[362.22294477843997, 452.0210137914681, 566.13...","[8.925436591790988e-07, 5.083358806623616, 8.0...",286,11,0.653310,1.278924,1.117940,1.144,0.597902,102.671668,0.132,1.276,0.816,31,33,319,204,-18,self-selected,180.0,76.0,23
1,11_1F_2,Right,"[14.019394623448846, 16.54752373052943, 18.458...","[1.026029499850483, 0.8009821609932601, 0.4176...","[88.11956142717656, 116.47818235269114, 147.54...","[22.191209060403597, 22.304023552664418, 22.44...","[13.606344174955472, 14.189785189696607, 14.83...","[7.992639049878598, 7.822939112077673, 7.63622...","[11.106311173373069, 17.004631066661812, 22.80...","[-11.623237519464524, -12.310145563421122, -12...","[-2.282079067271943, -3.271463104128628, -4.46...","[350.8691773260563, 351.83055343164006, 361.57...","[455.7122531312876, 484.37806130501565, 547.12...","[653.886955140613, 716.5097673832856, 813.0375...","[5.407310987679742e-11, 6.307605881972114e-09,...","[66.11529269705329, 32.735130377895764, 1.9716...","[4.731476188140097e-11, 5.379522917968298e-09,...","[147.4796339677098, 142.40576806106415, 141.56...","[7.810866650057915e-11, 8.978042484973225e-09,...","[76.3778536331347, 60.5071284669632, 56.458943...","[280.65043795478795, 324.296768993416, 392.342...","[1.1576766825634846e-09, 8.676547692965617, 13...",281,11,0.575531,1.228806,1.089367,1.128,0.613475,113.568087,0.688,1.816,1.380,31,172,454,345,-18,self-selected,180.0,76.0,23
2,11_1K_3,Left,"[9.429961991945866, 9.340841983225303, 8.16930...","[3.4425211943193355, 2.9945048919933983, 2.143...","[138.7897836900715, 181.53336237781622, 228.28...","[17.895441689720638, 18.109463768161685, 18.34...","[8.239329335860647, 8.945025919863918, 9.70789...","[7.831656644416162, 7.478930850804061, 7.09810...","[22.78806326481839, 29.979831210441002, 36.983...","[-14.272388807133616, -15.018760259452398, -14...","[-3.6531354512311824, -5.549440673363604, -7.8...","[415.38235006751023, 433.7150073900413, 523.22...","[629.11461721485, 718.8791806478171, 782.29753...","[962.8397283823093, 1110.524774710165, 1171.09...","[9.187064184845183e-10, 5.697195572078916e-09,...","[56.88031077288465, 14.749651061901128, 2.6207...","[8.441105569970356e-10, 5.7496904985480135e-09...","[170.70999554436202, 176.86849796418878, 218.4...","[1.4435282659132238e-09, 8.838779138101165e-09...","[115.64974425205095, 107.75072707865156, 75.81...","[422.0605383766697, 511.4376776942769, 560.479...","[1.14037694938436e-07, 6.839783427937151, 25.6...",286,11,0.698530,1.338955,1.170415,1.144,0.597902,100.532497,0.096,1.240,0.780,22,24,310,195,-18,constant,180.0,76.0,23
3,11_1K_3,Right,"[10.386012932655106, 9.53512269567237, 7.37720...","[8.140293625764647, 9.286994267355297, 10.2706...","[119.94664003379371, 158.57531760916373, 201.5...","[19.49775808106458, 19.701253204733273, 19.924...","[12.787580373406977, 13.561564317995675, 14.38...","[7.713202485879993, 7.493746397505441, 7.25453...","[11.513682094495506, 16.452024076036235, 21.04...","[-7.5648508951440645, -6.66735122355985, -4.90...","[-5.306948473009778, -7.162172800051598, -9.28...","[349.7386666441944, 458.07854810015874, 578.35...","[327.6868901138671, 356.7855578396026, 355.358...","[642.8465310816695, 670.1796472142004, 735.247...","[8.949862627158693e-08, 3.548017698943229e-08,...","[8.815070347499736e-09, 3.783138353967775e-10,...","[2.085122014868046e-08, 1.503551917724428e-09,...","[155.56041457364057, 203.92736467240016, 257.9...","[1.292434829496956e-07, 5.061166359741332e-08,...","[67.01899230507159, 29.83849272580364, 28.0899...","[213.1643418453964, 225.72105302320838, 216.65...","[12.625349179022976, 34.51506472716318, 87.897...",294,11,0.699632,1.398149,1.184872,1.180,0.593220,101.613868,0.660,1.840,1.360,22,165,460,340,-18,constant,180.0,76.0,23
4,11_2F_1,Left,"[-9.098609966945734, -12.61885424034078, -17.1...","[3.374502538740886, 4.031375084438764, 4.75680...","[165.08840022807746, 216.61540960689774, 272.9...","[19.086138939557287, 19.24169854251254, 19.415...","[6.162202286513988, 6.797498973017147, 7.49154...","[10.805377739583259, 10.512222624897953, 10.19...","[22.772753336697935, 28.315300410374366, 34.09...","[-10.964380870586663, -10.572041100968157, -9....","[-7.9129651429129915, -10.690688381174994, -13...","[593.0051455932584, 755.6464710469252, 932.936...","[550.5134056289367, 623.686301092125, 670.2149...","[912.5990166906339, 1007.3015915373205, 1137.5...","[2.032527435378688e-09, 6.522308834697417e-09,...","[1.7360543670884385e-10, 2.453428019468688e-10...","[4.941368773179446e-10, 7.558865552899786e-10,...","[256.82688113454617, 333.12124654066383, 418.0...","[3.3277355464871163e-09, 1.0537415519334869e-0...","[27.057709547071784, 1.1235656961623449e-06, 4...","[370.50180202485757, 405.6411237966206, 423.21...","[42.59115724532714, 62.33986091359603, 122.452...",295,11,0.685120,1.303506,1.104666,1.180,0.583051,96.742068,0.136,1.316,0.824,32,34,329,206,-12,self-selected,180.0,76.0,23

In [16]:
# labels for plotting
label_map = {
    "GRF_ap": "GRF Anterior-Posterior (N)",
    "GRF_ml": "GRF Medio-Lateral (N)",
    "GRF_vert": "GRF Vertical (N)",
    "angleHip": "Hip Angle (°)",
    "angleKnee": "Knee Angle (°)",
    "angleAnkle": "Ankle Angle (°)",
    "momentHip": "Hip Moment (Nm)",
    "momentKnee": "Knee Moment (Nm)",
    "momentAnkle": "Ankle Moment (Nm)",
    "ankleFres": "Ankle Joint Reaction Force (N)",
    "kneeFres": "Knee Joint Reaction Force (N)",
    "hipFres": "Hip Joint Reaction Force (N)",
    "knee_PFc": "Patellofemoral Contact Force (N)",
    "gastrocnemius": "Gastrocnemius Force (N)",
    "soleus": "Soleus Force (N)",
    "tib_ant": "Tibialis Anterior Force (N)",
    "quadriceps": "Quadriceps Force (N)",
    "iliopsoas": "Iliopsoas Force (N)",
    "hamstrings": "Hamstrings Force (N)"
}

In [18]:
import matplotlib.pyplot as plt
import matplotlib.lines as mlines
import matplotlib.patches as mpatches
import matplotlib.patheffects as pe
import numpy as np
from scipy.interpolate import interp1d
from scipy import stats

# ============================================================
# PEAK DETECTION LOGIC — max or min per variable per band
# ============================================================
# 'max' = find the highest point in the band (default)
# 'min' = find the lowest point (e.g. GRF P2 in downhill)

peak_logic = {
    #  variable       P1 band    P2 band
    'GRF_vert':   ('max',      'max'),   # P1 ↑ with slope, P2 ↓ with slope
                                          # but each curve's own peak is still max within band
    'kneeFres':   ('max',      'max'),
    'knee_PFc':   ('max',      'max'),
    'angleKnee':  ('max',      'max'),
    'momentKnee': ('max',      'max'),
}

# For the trend annotation we compare the peak value at 0° vs -18°
# If value decreases → annotate ↓, if increases → annotate ↑

# ============================================================
# CONFIGURATION (same as before)
# ============================================================
variables_to_plot = {
    'GRF_vert':   'Vertical Ground Reaction Force (×BW)',
    'kneeFres':   'Tibiofemoral Joint Compression Force (×BW)',
    'knee_PFc':   'Patellofemoral Joint Compression Force (×BW)',
    'angleKnee':  'Knee Flexion Angle (°)',
    'momentKnee': 'Knee Extension Moment (Nm)',
}
# Añade esto antes del for loop (línea ~74)
df_plot = df_p1.copy()  # o el dataframe que quieras visualizar
slopes_ordered = [0, -6, -12, -18]
slope_labels   = {0: '0°', -6: '−6°', -12: '−12°', -18: '−18°'}

colors_slope = {
    0:   '#a8d5e2',
   -6:   '#5b9fbf',
  -12:   '#2a6a96',
  -18:   '#0d2d55',
}
linestyles = {
    0:   (0, ()),
   -6:   (0, (6, 2)),
  -12:   (0, (3, 1, 1, 1)),
  -18:   (0, (1, 1)),
}

stance_pct      = np.linspace(0, 100, 101)
absorption_band = (10, 30)
propulsion_band = (65, 85)

def stance_interp(arr, stance_fraction):
    arr = np.array(arr, dtype=float)
    n = len(arr)
    if n < 2:
        return np.full(101, np.nan)
    n_stance = max(2, round(stance_fraction * n))
    arr_s = arr[:n_stance]
    x_orig = np.linspace(0, 100, len(arr_s))
    f = interp1d(x_orig, arr_s, kind='linear',
                 bounds_error=False, fill_value=np.nan)
    return f(stance_pct)

# ============================================================
# BUILD CURVES
# ============================================================
mean_curves = {var: {} for var in variables_to_plot}
std_curves  = {var: {} for var in variables_to_plot}

for slope in slopes_ordered:
    df_s = df_plot[df_plot['slope'] == slope]
    for var in variables_to_plot:
        all_trials = []
        for _, row in df_s.iterrows():
            val = row[var]
            sf  = row['stance']
            if isinstance(val, (list, np.ndarray)) and len(val) > 1:
                all_trials.append(stance_interp(val, sf))
        if all_trials:
            stack = np.array(all_trials)
            mean_curves[var][slope] = np.nanmean(stack, axis=0)
            std_curves[var][slope]  = np.nanstd(stack,  axis=0)
        else:
            mean_curves[var][slope] = np.full(101, np.nan)
            std_curves[var][slope]  = np.full(101, np.nan)

# ============================================================
# HELPER: find peak within a band (max or min)
# ============================================================
def find_peak(mean_curve, band, mode='max'):
    mask = (stance_pct >= band[0]) & (stance_pct <= band[1])
    seg  = mean_curve[mask]
    sp   = stance_pct[mask]
    if len(seg) == 0 or np.all(np.isnan(seg)):
        return None, None
    idx = np.nanargmax(seg) if mode == 'max' else np.nanargmin(seg)
    return sp[idx], seg[idx]

# ============================================================
# COMPUTE TREND DIRECTION per variable per band
# ============================================================
def get_trend(var, band, mode='max'):
    """Returns (symbol, color) based on whether value increases or decreases
    from 0° to -18°."""
    val_flat  = find_peak(mean_curves[var].get(0,  np.full(101, np.nan)), band, mode)[1]
    val_steep = find_peak(mean_curves[var].get(-18, np.full(101, np.nan)), band, mode)[1]
    if val_flat is None or val_steep is None:
        return '', 'gray'
    if val_steep > val_flat:
        return '↑', '#c62828'   # red = increases with steeper slope
    else:
        return '↓', '#1565c0'   # blue = decreases with steeper slope

# ============================================================
# PLOT
# ============================================================
for var, ylabel in variables_to_plot.items():

    p1_mode = peak_logic.get(var, ('max', 'max'))[0]
    p2_mode = peak_logic.get(var, ('max', 'max'))[1]

    fig, ax = plt.subplots(figsize=(7.5, 5))

    # Phase shading
    ax.axvspan(*absorption_band, alpha=0.10, color='#2196F3', zorder=0)
    ax.axvspan(*propulsion_band, alpha=0.10, color='#FF7043', zorder=0)
    ax.text(np.mean(absorption_band), 0.97, 'Absorption',
            transform=ax.get_xaxis_transform(),
            ha='center', va='top', fontsize=8,
            color='#0d47a1', fontstyle='italic', fontweight='bold')
    ax.text(np.mean(propulsion_band), 0.97, 'Propulsion',
            transform=ax.get_xaxis_transform(),
            ha='center', va='top', fontsize=8,
            color='#bf360c', fontstyle='italic', fontweight='bold')

    # Lines + SD bands
    for slope in slopes_ordered:
        mean = mean_curves[var].get(slope)
        sd   = std_curves[var].get(slope)
        if mean is None or np.all(np.isnan(mean)):
            continue
        color = colors_slope[slope]
        ax.fill_between(stance_pct, mean - sd, mean + sd,
                        color=color, alpha=0.15, zorder=2)
        ax.plot(stance_pct, mean, color=color, linewidth=2.0,
                linestyle=linestyles[slope], zorder=3)

    # Circles at P1 / P2 per slope
    for slope in slopes_ordered:
        mean = mean_curves[var].get(slope)
        if mean is None or np.all(np.isnan(mean)):
            continue
        color = colors_slope[slope]

        px1, py1 = find_peak(mean, absorption_band, p1_mode)
        if px1 is not None:
            ax.plot(px1, py1, 'o', color=color, markersize=7,
                    markeredgecolor='white', markeredgewidth=1.2, zorder=6)

        px2, py2 = find_peak(mean, propulsion_band, p2_mode)
        if px2 is not None:
            ax.plot(px2, py2, 'o', color=color, markersize=7,
                    markeredgecolor='white', markeredgewidth=1.2, zorder=6)

    # Trend annotations (↑ / ↓) inside the bands
    ymin, ymax = ax.get_ylim()
    y_range    = ymax - ymin

    sym1, col1 = get_trend(var, absorption_band, p1_mode)
    sym2, col2 = get_trend(var, propulsion_band, p2_mode)

    # P1 label + trend
    ax.text(np.mean(absorption_band), ymin + y_range * 0.06,
            f'P1  {sym1}',
            ha='center', fontsize=9, fontweight='bold',
            color=col1, zorder=7)

    # P2 label + trend
    ax.text(np.mean(propulsion_band), ymin + y_range * 0.06,
            f'P2  {sym2}',
            ha='center', fontsize=9, fontweight='bold',
            color=col2, zorder=7)

    # Add a small note for GRF explaining the P2 decrease
    if var == 'GRF_vert':
        ax.text(0.98, 0.30,
                'P2 ↓ with steeper slope:\nreduced push-off demand\n(gravity assists propulsion)',
                transform=ax.transAxes, ha='right', va='top',
                fontsize=7.5, color='#1565c0', style='italic',
                bbox=dict(boxstyle='round,pad=0.4', facecolor='white',
                          edgecolor='#bbbbbb', alpha=0.85))

    # Slope legend
    slope_handles = [
        mlines.Line2D([], [], color=colors_slope[s], linestyle=linestyles[s],
                      linewidth=2.0, label=slope_labels[s])
        for s in slopes_ordered
    ]
    leg1 = ax.legend(handles=slope_handles, title='Slope', title_fontsize=8.5,
                     loc='upper right', fontsize=8.5,
                     framealpha=0.92, edgecolor='#cccccc')
    ax.add_artist(leg1)

    # Phase legend
    phase_handles = [
        mpatches.Patch(color='#2196F3', alpha=0.4,
                       label=f'Absorption ({absorption_band[0]}–{absorption_band[1]}%)'),
        mpatches.Patch(color='#FF7043', alpha=0.4,
                       label=f'Propulsion ({propulsion_band[0]}–{propulsion_band[1]}%)'),
    ]
    ax.legend(handles=phase_handles, loc='lower right',
              fontsize=7.5, framealpha=0.92, edgecolor='#cccccc')

    # Axes
    ax.set_xlabel('Gait Cycle (%)', fontsize=11, labelpad=5)
    ax.set_ylabel(ylabel, fontsize=10, labelpad=5)
    ax.set_title(ylabel.split('(')[0].strip(),
                 fontsize=12, fontweight='bold', pad=12)
    ax.set_xlim(0, 100)
    ax.set_xticks(range(0, 101, 25))
    ax.grid(True, linestyle=':', alpha=0.4, color='#aaaaaa')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.tick_params(labelsize=9)

    plt.tight_layout()
    plt.show()

# ============================================================
# PRINT PEAK VALUES PER BAND TO CONFIRM TRENDS
# ============================================================
print("\n" + "="*70)
print("PEAK VALUES PER PHASE BAND — confirming trend directions")
print("="*70)
print(f"\n{'Variable':<30} {'Band':<14} {'0°':>8} {'−6°':>8} {'−12°':>8} {'−18°':>8}  Trend")
print("-"*70)

for var, label in variables_to_plot.items():
    short = label.split('(')[0].strip()[:28]
    p1_mode = peak_logic.get(var, ('max','max'))[0]
    p2_mode = peak_logic.get(var, ('max','max'))[1]

    for band_name, band, mode in [('Absorption', absorption_band, p1_mode),
                                   ('Propulsion', propulsion_band, p2_mode)]:
        vals = []
        for slope in slopes_ordered:
            mean = mean_curves[var].get(slope, np.full(101, np.nan))
            _, pv = find_peak(mean, band, mode)
            vals.append(pv)

        trend = '↑' if (vals[-1] is not None and vals[0] is not None
                        and vals[-1] > vals[0]) else '↓'
        col   = '\033[31m' if trend == '↑' else '\033[34m'
        reset = '\033[0m'
        row   = [f"{v:.2f}" if v is not None else " nan" for v in vals]
        print(f"{short:<30} {band_name:<14} "
              f"{row[0]:>8} {row[1]:>8} {row[2]:>8} {row[3]:>8}  "
              f"{col}{trend}{reset}")

print()
print("↑ = increases with steeper downhill slope")
print("↓ = decreases with steeper downhill slope")
print("\nNote: GRF P2 ↓ is consistent with Alexander & Schwameder (2016):")
print("  'decreased vertical GRF at the second peak' during downhill walking")

NameError: name 'df_p1' is not defined

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.lines as mlines
import matplotlib.patches as mpatches
import numpy as np
from scipy.interpolate import interp1d
from scipy import stats
import os

# ============================================================
# STEP 0 — OUTPUT FOLDER
# ============================================================
os.makedirs("figures", exist_ok=True)

# ============================================================
# STEP 1 — NORMALIZE FORCE COLUMNS TO ×BW IN df_merged
# ============================================================
force_cols_to_normalize = ['kneeFres', 'knee_PFc', 'GRF_vert',
                            'ankleFres', 'hipFres',
                            'GRF_ap', 'GRF_ml']

df_plot = df_merged.copy()

for idx, row in df_plot.iterrows():
    bw = row['weight'] * 9.81
    if bw <= 0:
        continue
    for col in force_cols_to_normalize:
        val = row[col]
        if isinstance(val, (list, np.ndarray)) and len(val) > 1:
            df_plot.at[idx, col] = np.array(val, dtype=float) / bw
        elif isinstance(val, (int, float)):
            df_plot.at[idx, col] = val / bw

print("✓ Force columns normalized to ×BW")
print(f"  Columns normalized : {force_cols_to_normalize}")
print(f"  Mean body weight   : {df_plot['weight'].mean():.1f} kg "
      f"({(df_plot['weight'] * 9.81).mean():.1f} N)")

# ============================================================
# STEP 2 — CONFIGURATION
# ============================================================
variables_to_plot = {
    'GRF_vert':   'Vertical Ground Reaction Force (×BW)',
    'kneeFres':   'Tibiofemoral Joint Compression Force (×BW)',
    'knee_PFc':   'Patellofemoral Joint Compression Force (×BW)',
    'angleKnee':  'Knee Flexion Angle (°)',
    'momentKnee': 'Knee Extension Moment (Nm)',
}

# Peak detection logic: 'max' or 'min' per (P1 band, P2 band)
peak_logic = {
    'GRF_vert':   ('max', 'max'),
    'kneeFres':   ('max', 'max'),
    'knee_PFc':   ('max', 'max'),
    'angleKnee':  ('max', 'max'),
    'momentKnee': ('max', 'max'),
}

slopes_ordered = [0, -6, -12, -18]
slope_labels   = {0: '0°', -6: '−6°', -12: '−12°', -18: '−18°'}

colors_slope = {
    0:   '#a8d5e2',
   -6:   '#5b9fbf',
  -12:   '#2a6a96',
  -18:   '#0d2d55',
}
linestyles = {
    0:   (0, ()),
   -6:   (0, (6, 2)),
  -12:   (0, (3, 1, 1, 1)),
  -18:   (0, (1, 1)),
}

stance_pct      = np.linspace(0, 100, 101)
absorption_band = (10, 30)
propulsion_band = (65, 85)

# ============================================================
# STEP 3 — HELPERS
# ============================================================
def stance_interp(arr, stance_fraction):
    arr = np.array(arr, dtype=float)
    n = len(arr)
    if n < 2:
        return np.full(101, np.nan)
    n_stance = max(2, round(stance_fraction * n))
    arr_s    = arr[:n_stance]
    x_orig   = np.linspace(0, 100, len(arr_s))
    f = interp1d(x_orig, arr_s, kind='linear',
                 bounds_error=False, fill_value=np.nan)
    return f(stance_pct)


def find_peak(mean_curve, band, mode='max'):
    mask = (stance_pct >= band[0]) & (stance_pct <= band[1])
    seg  = mean_curve[mask]
    sp   = stance_pct[mask]
    if len(seg) == 0 or np.all(np.isnan(seg)):
        return None, None
    idx = np.nanargmax(seg) if mode == 'max' else np.nanargmin(seg)
    return sp[idx], seg[idx]


def get_trend(var, band, mode='max'):
    val_flat  = find_peak(mean_curves[var].get(0,   np.full(101, np.nan)), band, mode)[1]
    val_steep = find_peak(mean_curves[var].get(-18, np.full(101, np.nan)), band, mode)[1]
    if val_flat is None or val_steep is None:
        return '', 'gray'
    if val_steep > val_flat:
        return '↑', '#c62828'
    else:
        return '↓', '#1565c0'

# ============================================================
# STEP 4 — BUILD MEAN ± SD CURVES PER SLOPE
# ============================================================
mean_curves = {var: {} for var in variables_to_plot}
std_curves  = {var: {} for var in variables_to_plot}

for slope in slopes_ordered:
    df_s = df_plot[df_plot['slope'] == slope]
    for var in variables_to_plot:
        all_trials = []
        for _, row in df_s.iterrows():
            val = row[var]
            sf  = row['stance']
            if isinstance(val, (list, np.ndarray)) and len(val) > 1:
                all_trials.append(stance_interp(val, sf))
        if all_trials:
            stack = np.array(all_trials)
            mean_curves[var][slope] = np.nanmean(stack, axis=0)
            std_curves[var][slope]  = np.nanstd(stack,  axis=0)
        else:
            mean_curves[var][slope] = np.full(101, np.nan)
            std_curves[var][slope]  = np.full(101, np.nan)

# ============================================================
# STEP 5 — PLOT + EXPORT
# ============================================================
for var, ylabel in variables_to_plot.items():

    p1_mode = peak_logic.get(var, ('max', 'max'))[0]
    p2_mode = peak_logic.get(var, ('max', 'max'))[1]

    fig, ax = plt.subplots(figsize=(7.5, 5))

    # --- Phase shading ---
    ax.axvspan(*absorption_band, alpha=0.10, color='#2196F3', zorder=0)
    ax.axvspan(*propulsion_band, alpha=0.10, color='#FF7043', zorder=0)
    ax.text(np.mean(absorption_band), 0.97, 'Absorption',
            transform=ax.get_xaxis_transform(),
            ha='center', va='top', fontsize=8,
            color='#0d47a1', fontstyle='italic', fontweight='bold')
    ax.text(np.mean(propulsion_band), 0.97, 'Propulsion',
            transform=ax.get_xaxis_transform(),
            ha='center', va='top', fontsize=8,
            color='#bf360c', fontstyle='italic', fontweight='bold')

    # --- Mean ± SD lines per slope ---
    for slope in slopes_ordered:
        mean = mean_curves[var].get(slope)
        sd   = std_curves[var].get(slope)
        if mean is None or np.all(np.isnan(mean)):
            continue
        color = colors_slope[slope]
        ax.fill_between(stance_pct, mean - sd, mean + sd,
                        color=color, alpha=0.15, zorder=2)
        ax.plot(stance_pct, mean, color=color, linewidth=2.0,
                linestyle=linestyles[slope], zorder=3)

    # --- Circles at P1 / P2 per slope ---
    for slope in slopes_ordered:
        mean = mean_curves[var].get(slope)
        if mean is None or np.all(np.isnan(mean)):
            continue
        color = colors_slope[slope]

        px1, py1 = find_peak(mean, absorption_band, p1_mode)
        if px1 is not None:
            ax.plot(px1, py1, 'o', color=color, markersize=7,
                    markeredgecolor='white', markeredgewidth=1.2, zorder=6)

        px2, py2 = find_peak(mean, propulsion_band, p2_mode)
        if px2 is not None:
            ax.plot(px2, py2, 'o', color=color, markersize=7,
                    markeredgecolor='white', markeredgewidth=1.2, zorder=6)

    # --- P1 / P2 trend labels ---
    ymin, ymax = ax.get_ylim()
    y_range    = ymax - ymin

    sym1, col1 = get_trend(var, absorption_band, p1_mode)
    sym2, col2 = get_trend(var, propulsion_band, p2_mode)

    ax.text(np.mean(absorption_band), ymin + y_range * 0.06,
            f'P1  {sym1}', ha='center', fontsize=9,
            fontweight='bold', color=col1, zorder=7)
    ax.text(np.mean(propulsion_band), ymin + y_range * 0.06,
            f'P2  {sym2}', ha='center', fontsize=9,
            fontweight='bold', color=col2, zorder=7)

    # --- Explanatory note for GRF only ---
    if var == 'GRF_vert':
        ax.text(0.98, 0.30,
                'P2 ↓ with steeper slope:\nreduced push-off demand\n'
                '(gravity assists propulsion)',
                transform=ax.transAxes, ha='right', va='top',
                fontsize=7.5, color='#1565c0', style='italic',
                bbox=dict(boxstyle='round,pad=0.4', facecolor='white',
                          edgecolor='#bbbbbb', alpha=0.85))

    # --- Slope legend ---
    slope_handles = [
        mlines.Line2D([], [], color=colors_slope[s], linestyle=linestyles[s],
                      linewidth=2.0, label=slope_labels[s])
        for s in slopes_ordered
    ]
    leg1 = ax.legend(handles=slope_handles, title='Slope', title_fontsize=8.5,
                     loc='upper right', fontsize=8.5,
                     framealpha=0.92, edgecolor='#cccccc')
    ax.add_artist(leg1)

    # --- Phase legend ---
    phase_handles = [
        mpatches.Patch(color='#2196F3', alpha=0.4,
                       label=f'Absorption ({absorption_band[0]}–{absorption_band[1]}%)'),
        mpatches.Patch(color='#FF7043', alpha=0.4,
                       label=f'Propulsion ({propulsion_band[0]}–{propulsion_band[1]}%)'),
    ]
    ax.legend(handles=phase_handles, loc='lower right',
              fontsize=7.5, framealpha=0.92, edgecolor='#cccccc')

    # --- Axes formatting ---
    ax.set_xlabel('Gait Cycle (%)', fontsize=11, labelpad=5)
    ax.set_ylabel(ylabel, fontsize=10, labelpad=5)
    ax.set_title(ylabel.split('(')[0].strip(),
                 fontsize=12, fontweight='bold', pad=12)
    ax.set_xlim(0, 100)
    ax.set_xticks(range(0, 101, 25))
    ax.grid(True, linestyle=':', alpha=0.4, color='#aaaaaa')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.tick_params(labelsize=9)

    plt.tight_layout()

    # --- Export ---
    fig.savefig(f"figures/{var}.png", dpi=300,
                bbox_inches='tight', facecolor='white')
    print(f"✓ Saved: figures/{var}.png")

    plt.show()

# ============================================================
# STEP 6 — SUMMARY TABLES
# ============================================================
mean_stance_data = {var: {s: [] for s in slopes_ordered} for var in variables_to_plot}
peak_data        = {var: {s: [] for s in slopes_ordered} for var in variables_to_plot}

for var in variables_to_plot:
    for slope in slopes_ordered:
        df_s = df_plot[df_plot['slope'] == slope]
        for _, row in df_s.iterrows():
            val = row[var]
            sf  = row['stance']
            if isinstance(val, (list, np.ndarray)) and len(val) > 1:
                curve = stance_interp(val, sf)
                mean_stance_data[var][slope].append(np.nanmean(curve))
                peak_data[var][slope].append(np.nanmax(curve))

# --- Table 1: mean over stance ---
print("\n" + "="*80)
print("TABLE 1 — MEAN OVER STANCE PHASE  (comparable to Alexander 2016, Table 1)")
print("Forces in ×BW | Angles in ° | Moments in Nm")
print("="*80)
print(f"\n{'Variable':<42} {'0°':>9} {'−6°':>9} {'−12°':>9} {'−18°':>9}")
print("-"*80)

for var, label in variables_to_plot.items():
    short   = label.split('(')[0].strip()
    row_str = []
    for slope in slopes_ordered:
        vals = mean_stance_data[var][slope]
        m = np.nanmean(vals) if vals else np.nan
        s = np.nanstd(vals)  if vals else np.nan
        row_str.append(f"{m:.2f}±{s:.2f}")
    print(f"{short:<42} {row_str[0]:>9} {row_str[1]:>9} {row_str[2]:>9} {row_str[3]:>9}")

print("\n  Reference — Alexander & Schwameder (2016) Table 1 (mean ×BW):")
print(f"  {'Tibiofemoral compression':<40} {'2.38':>9} {'2.32':>9} {'2.81':>9} {'3.04':>9}")
print(f"  {'Patellofemoral compression':<40} {'0.23':>9} {'0.54':>9} {'1.36':>9} {'2.03':>9}")

# --- Table 2: peak ---
print("\n" + "="*80)
print("TABLE 2 — PEAK (MAXIMUM) VALUE  (comparable to Alexander 2016, Table 2)")
print("Forces in ×BW | Angles in ° | Moments in Nm")
print("="*80)
print(f"\n{'Variable':<42} {'0°':>9} {'−6°':>9} {'−12°':>9} {'−18°':>9}")
print("-"*80)

for var, label in variables_to_plot.items():
    short   = label.split('(')[0].strip()
    row_str = []
    for slope in slopes_ordered:
        vals = peak_data[var][slope]
        m = np.nanmean(vals) if vals else np.nan
        s = np.nanstd(vals)  if vals else np.nan
        row_str.append(f"{m:.2f}±{s:.2f}")
    print(f"{short:<42} {row_str[0]:>9} {row_str[1]:>9} {row_str[2]:>9} {row_str[3]:>9}")

print("\n  Reference — Alexander & Schwameder (2016) Table 2 (maximum ×BW):")
print(f"  {'Tibiofemoral compression':<40} {'4.09':>9} {'3.77':>9} {'4.88':>9} {'5.50':>9}")
print(f"  {'Patellofemoral compression':<40} {'0.86':>9} {'1.46':>9} {'2.78':>9} {'3.96':>9}")

# ============================================================
# STEP 7 — STATISTICS
# ============================================================
print("\n" + "="*80)
print("STATISTICS — Effect of inclination (one-way ANOVA + Pearson r)")
print("="*80)

for label_type, data_dict in [("MEAN OVER STANCE", mean_stance_data),
                               ("PEAK (MAXIMUM)",   peak_data)]:

    print(f"\n  [{label_type}]")
    print(f"  {'Variable':<42} {'r':>6} {'p (ANOVA)':>11}  Trend")
    print("  " + "-"*72)

    for var, label in variables_to_plot.items():
        short  = label.split('(')[0].strip()
        groups = [data_dict[var][s] for s in slopes_ordered
                  if data_dict[var][s]]

        all_s, all_v = [], []
        for s in slopes_ordered:
            for v in data_dict[var][s]:
                all_s.append(s); all_v.append(v)

        r,  _   = stats.pearsonr(all_s, all_v) if len(all_v) > 3 else (np.nan, np.nan)
        _, p_av = stats.f_oneway(*groups)       if len(groups) >= 2 else (np.nan, np.nan)

        sig       = '  *' if p_av < 0.05 else ' ns'
        direction = ('↑ increases with steeper slope'
                     if r < 0 else '↓ decreases with steeper slope')

        print(f"  {short:<42} {r:>+6.3f} {p_av:>10.4f}{sig}  {direction}")

print("\n  * p < 0.05  (one-way ANOVA across slopes 0°, −6°, −12°, −18°)")
print("  r = Pearson correlation (negative r → steeper slope = higher value)")

In [ ]:
Improve this analysis by covariate fixed ID per participant

In [9]:
import statsmodels.formula.api as smf
import numpy as np
import pandas as pd

# ============================================================
# FIXED HELPER FUNCTIONS
# ============================================================

def run_ols_with_subject(df_long, outcome_col):
    df_clean = df_long[['id', 'slope', outcome_col]].dropna().copy()
    # Force slope to plain Python int so formula keys are clean
    df_clean['slope'] = df_clean['slope'].astype(int)
    df_clean['id']    = df_clean['id'].astype(str)
    formula = f"{outcome_col} ~ C(slope, Treatment(0)) + C(id)"
    model   = smf.ols(formula, data=df_clean).fit()
    return model, df_clean


def extract_slope_results(model, slopes_vs):
    results = {}
    params  = model.params
    pvalues = model.pvalues
    tvalues = model.tvalues
    conf    = model.conf_int()
    df_res  = model.df_resid

    # Debug: show available keys if needed
    slope_keys = [k for k in params.index if 'slope' in k.lower()]

    for slope in slopes_vs:
        # Try both possible key formats
        key1 = f"C(slope, Treatment(0))[T.{int(slope)}]"
        key2 = f"C(slope, Treatment(0))[T.{slope}]"
        key  = key1 if key1 in params else (key2 if key2 in params else None)

        if key:
            coef       = params[key]
            p          = pvalues[key]
            t          = tvalues[key]
            ci_lo, ci_hi = conf.loc[key]
            dz         = abs(t) / np.sqrt(df_res + 1)

            if   dz >= 0.80: size = 'L'
            elif dz >= 0.50: size = 'M'
            elif dz >= 0.20: size = 'S'
            else:            size = 'trivial'

            results[slope] = {
                'coef':      coef,
                'p':         p,
                't':         t,
                'ci_lo':     ci_lo,
                'ci_hi':     ci_hi,
                'dz':        dz,
                'size':      size,
                'sig':       '*'  if p < alpha_bonferroni else 'ns',
                'direction': '↑'  if coef > 0 else '↓',
            }
        else:
            results[slope] = None
            print(f"    ⚠ Key not found for slope={slope}. Available: {slope_keys}")

    return results


# ============================================================
# STEP 10 — SIGNIFICANCE TABLE
# ============================================================
n_comparisons    = 3
alpha_bonferroni = 0.05 / n_comparisons
slopes_vs        = [-6, -12, -18]

for metric_label, suffix in [("MEAN OVER STANCE", "_mean"),
                              ("PEAK (MAXIMUM)",   "_peak")]:

    print("\n" + "="*105)
    print(f"OLS WITH SUBJECT AS FIXED COVARIATE — {metric_label}")
    print(f"Model: outcome ~ C(slope) + C(id)  |  Reference = 0°")
    print(f"Bonferroni α = 0.05 / {n_comparisons} = {alpha_bonferroni:.4f}")
    print("="*105)
    print(f"\n  {'Variable':<38} {'R²':>5}  "
          f"{'vs −6°':>24} {'vs −12°':>24} {'vs −18°':>24}")
    print("  " + "-"*115)

    for var, label in variables_to_plot.items():
        short = label.split('(')[0].strip()[:36]
        col   = f'{var}{suffix}'

        model, _ = run_ols_with_subject(df_long, col)
        res      = extract_slope_results(model, slopes_vs)
        r2       = model.rsquared

        cols_str = []
        for slope in slopes_vs:
            r = res.get(slope)
            if r is None:
                cols_str.append("              n/a")
            else:
                cols_str.append(
                    f"{r['direction']} p={r['p']:.4f}{r['sig']} "
                    f"dz={r['dz']:.2f}({r['size']})"
                )
        print(f"  {short:<38} {r2:>5.3f}  "
              f"{cols_str[0]:>24} {cols_str[1]:>24} {cols_str[2]:>24}")

    print(f"\n  * p < {alpha_bonferroni:.4f} (Bonferroni)")


# ============================================================
# STEP 11 — COEFFICIENTS TABLE with 95% CI
# ============================================================
print("\n\n" + "="*105)
print("COEFFICIENTS vs. LEVEL (0°)  —  Δ change in units  [95% CI]")
print("Controlling for participant ID as fixed covariate")
print("Forces in ×BW | Angles in ° | Moments in Nm")
print("="*105)

for metric_label, suffix in [("MEAN OVER STANCE", "_mean"),
                              ("PEAK (MAXIMUM)",   "_peak")]:

    print(f"\n  [{metric_label}]")
    print(f"  {'Variable':<38} "
          f"{'Δ −6° [95%CI]':>26} "
          f"{'Δ −12° [95%CI]':>26} "
          f"{'Δ −18° [95%CI]':>26}")
    print("  " + "-"*118)

    for var, label in variables_to_plot.items():
        short = label.split('(')[0].strip()[:36]
        col   = f'{var}{suffix}'

        model, _ = run_ols_with_subject(df_long, col)
        res      = extract_slope_results(model, slopes_vs)

        cols_str = []
        for slope in slopes_vs:
            r = res.get(slope)
            if r is None:
                cols_str.append("                   n/a")
            else:
                cols_str.append(
                    f"{r['coef']:+.3f} [{r['ci_lo']:+.3f}, {r['ci_hi']:+.3f}]{r['sig']}"
                )

        print(f"  {short:<38} "
              f"{cols_str[0]:>26} "
              f"{cols_str[1]:>26} "
              f"{cols_str[2]:>26}")

print(f"\n  * p < {alpha_bonferroni:.4f} (Bonferroni)")
print("  Δ = estimated change vs. level walking (0°), controlling for participant")
print("  Positive Δ = higher than level | Negative Δ = lower than level")

=========================================================================================================
OLS WITH SUBJECT AS FIXED COVARIATE — MEAN OVER STANCE
Model: outcome ~ C(slope) + C(id)  |  Reference = 0°
Bonferroni α = 0.05 / 3 = 0.0167
=========================================================================================================

  Variable                                  R²                    vs −6°                  vs −12°                  vs −18°
  -------------------------------------------------------------------------------------------------------------------

NameError: name 'df_long' is not defined

In [ ]:
# DIAGNÓSTICO — ejecuta esto PRIMERO antes de cualquier otra cosa
print("Conditions:", df_merged['condition'].unique())
print("Slopes    :", sorted(df_merged['slope'].unique()))
print("Columns   :", df_merged.columns.tolist())

In [ ]:
# ============================================================
# BUILD df_peak1 and df_peak2 FROM df_merged
# Extracting scalar values at P1 (absorption) and P2 (propulsion)
# ============================================================

from scipy.interpolate import interp1d
import numpy as np
import pandas as pd

# Bands (% of stance)
absorption_band = (10, 30)   # P1
propulsion_band = (65, 85)   # P2

stance_pct = np.linspace(0, 100, 101)

# Variables with time series to extract peaks from
ts_vars = ['kneeFres', 'knee_PFc', 'GRF_vert', 'GRF_ap',
           'angleKnee', 'angleHip', 'angleAnkle',
           'momentKnee', 'momentHip', 'momentAnkle',
           'ankleFres', 'hipFres']

# Metadata columns to keep
meta_cols = ['id', 'file', 'side', 'slope', 'condition',
             'height', 'weight', 'age', 'speed',
             'step_length', 'stride_length', 'gc_dur',
             'stance', 'cadence']

def interp_stance(arr, stance_fraction):
    """Crop to stance phase and interpolate to 101 points."""
    arr = np.array(arr, dtype=float)
    n = len(arr)
    if n < 2:
        return np.full(101, np.nan)
    n_stance = max(2, round(stance_fraction * n))
    arr_s    = arr[:n_stance]
    x_orig   = np.linspace(0, 100, len(arr_s))
    f = interp1d(x_orig, arr_s, kind='linear',
                 bounds_error=False, fill_value=np.nan)
    return f(stance_pct)

def extract_peak_in_band(curve, band, mode='max'):
    """Return scalar peak value within a % stance band."""
    mask = (stance_pct >= band[0]) & (stance_pct <= band[1])
    seg  = curve[mask]
    if len(seg) == 0 or np.all(np.isnan(seg)):
        return np.nan
    return np.nanmax(seg) if mode == 'max' else np.nanmin(seg)

# Peak detection mode per variable per band
# GRF_ap at P1 is negative (braking) → use min
peak_modes = {
    'GRF_ap': ('min', 'max'),   # P1=braking(negative), P2=propulsion(positive)
}

rows_p1 = []
rows_p2 = []

for _, row in df_merged.iterrows():
    sf = row['stance']

    # Metadata
    meta = {col: row[col] for col in meta_cols if col in row.index}

    entry_p1 = meta.copy()
    entry_p2 = meta.copy()

    for var in ts_vars:
        if var not in row.index:
            entry_p1[var] = np.nan
            entry_p2[var] = np.nan
            continue

        val = row[var]
        if not isinstance(val, (list, np.ndarray)) or len(val) < 2:
            entry_p1[var] = np.nan
            entry_p2[var] = np.nan
            continue

        curve = interp_stance(val, sf)

        p1_mode, p2_mode = peak_modes.get(var, ('max', 'max'))
        entry_p1[var] = extract_peak_in_band(curve, absorption_band, p1_mode)
        entry_p2[var] = extract_peak_in_band(curve, propulsion_band, p2_mode)

    rows_p1.append(entry_p1)
    rows_p2.append(entry_p2)

df_peak1 = pd.DataFrame(rows_p1)
df_peak2 = pd.DataFrame(rows_p2)

# Fix types
for df_ in [df_peak1, df_peak2]:
    df_['id']    = df_['id'].astype(str).str.strip()
    df_['slope'] = df_['slope'].astype(int)

# Exclude participants 16 & 26
exclude  = ['16', '26']
df_peak1 = df_peak1[~df_peak1['id'].isin(exclude)].copy()
df_peak2 = df_peak2[~df_peak2['id'].isin(exclude)].copy()

# Normalize forces to ×BW
force_cols = ['kneeFres', 'knee_PFc', 'GRF_vert', 'GRF_ap',
              'ankleFres', 'hipFres']
for df_ in [df_peak1, df_peak2]:
    for col in force_cols:
        if col in df_.columns:
            df_[col] = df_[col] / (df_['weight'] * 9.81)

print("✓ df_peak1 and df_peak2 built from df_merged")
print(f"\n  PEAK 1 (Absorption band {absorption_band[0]}–{absorption_band[1]}% stance)")
print(f"    Rows         : {len(df_peak1)}")
print(f"    Participants : {df_peak1['id'].nunique()}")
print(f"    Slopes       : {sorted(df_peak1['slope'].unique())}")
print(f"    Conditions   : {df_peak1['condition'].unique()}")

print(f"\n  PEAK 2 (Propulsion band {propulsion_band[0]}–{propulsion_band[1]}% stance)")
print(f"    Rows         : {len(df_peak2)}")
print(f"    Participants : {df_peak2['id'].nunique()}")
print(f"    Slopes       : {sorted(df_peak2['slope'].unique())}")
print(f"    Conditions   : {df_peak2['condition'].unique()}")

print(f"\n  Sample means at 0° — PEAK 1:")
for var in ['kneeFres', 'knee_PFc', 'GRF_vert']:
    m = df_peak1[df_peak1['slope']==0][var].mean()
    print(f"    {var:<15}: {m:.3f} ×BW")

print(f"\n  Sample means at 0° — PEAK 2:")
for var in ['kneeFres', 'knee_PFc', 'GRF_vert']:
    m = df_peak2[df_peak2['slope']==0][var].mean()
    print(f"    {var:<15}: {m:.3f} ×BW")

In [ ]:
# ============================================================
# OLS WITH SUBJECT AS FIXED COVARIATE — PEAK 1 vs PEAK 2
# ============================================================

import statsmodels.formula.api as smf

variables_scalar = {
    'kneeFres':   'Tibiofemoral Joint Compression Force (×BW)',
    'knee_PFc':   'Patellofemoral Joint Compression Force (×BW)',
    'GRF_vert':   'Vertical Ground Reaction Force (×BW)',
    'angleKnee':  'Knee Flexion Angle (°)',
    'momentKnee': 'Knee Extension Moment (Nm)',
}

slopes_vs        = [-6, -12, -18]
n_comparisons    = 3
alpha_bonferroni = 0.05 / n_comparisons  # 0.0167


def run_ols_scalar(df, outcome_col):
    df_clean = df[['id', 'slope', outcome_col]].dropna().copy()
    df_clean['slope'] = df_clean['slope'].astype(int)
    df_clean['id']    = df_clean['id'].astype(str)
    formula = f"{outcome_col} ~ C(slope, Treatment(0)) + C(id)"
    return smf.ols(formula, data=df_clean).fit()


def extract_results(model, slopes_vs):
    params  = model.params
    pvalues = model.pvalues
    tvalues = model.tvalues
    conf    = model.conf_int()
    df_res  = model.df_resid
    results = {}

    for slope in slopes_vs:
        key = f"C(slope, Treatment(0))[T.{int(slope)}]"
        if key in params:
            coef         = params[key]
            p            = pvalues[key]
            t            = tvalues[key]
            ci_lo, ci_hi = conf.loc[key]
            dz           = abs(t) / np.sqrt(df_res + 1)

            if   dz >= 0.80: size = 'L'
            elif dz >= 0.50: size = 'M'
            elif dz >= 0.20: size = 'S'
            else:            size = 'trivial'

            results[slope] = {
                'coef': coef, 'p': p,
                'ci_lo': ci_lo, 'ci_hi': ci_hi,
                'dz': dz, 'size': size,
                'sig': '*' if p < alpha_bonferroni else 'ns',
                'direction': '↑' if coef > 0 else '↓',
            }
        else:
            results[slope] = None
    return results


# ============================================================
# PRINT RESULTS
# ============================================================

for peak_label, df_ in [
        ("PEAK 1 — Absorption phase (10–30% stance)", df_peak1),
        ("PEAK 2 — Propulsion phase (65–85% stance)", df_peak2)]:

    print("\n" + "="*108)
    print(f"OLS — {peak_label}")
    print(f"Model: value ~ C(slope) + C(id)  |  Reference = 0°  |  Excl: 16 & 26")
    print(f"Bonferroni α = {alpha_bonferroni:.4f}  |  "
          f"Effect: L>0.80 | M=0.50–0.79 | S=0.20–0.49 | trivial<0.20")
    print("="*108)

    # --- Significance table ---
    print(f"\n  {'Variable':<38} {'R²':>5}  "
          f"{'vs −6°':>24} {'vs −12°':>24} {'vs −18°':>24}")
    print("  " + "-"*118)

    for var, label in variables_scalar.items():
        if var not in df_.columns:
            continue
        short = label.split('(')[0].strip()[:36]
        model = run_ols_scalar(df_, var)
        res   = extract_results(model, slopes_vs)
        r2    = model.rsquared

        cols_str = []
        for slope in slopes_vs:
            r = res.get(slope)
            if r is None:
                cols_str.append("                   n/a")
            else:
                cols_str.append(
                    f"{r['direction']} p={r['p']:.4f}{r['sig']} "
                    f"dz={r['dz']:.2f}({r['size']})"
                )
        print(f"  {short:<38} {r2:>5.3f}  "
              f"{cols_str[0]:>24} {cols_str[1]:>24} {cols_str[2]:>24}")

    # --- Coefficients table ---
    print(f"\n  Δ vs. level (0°)  [95% CI]")
    print(f"  {'Variable':<38} "
          f"{'Δ −6° [95%CI]':>28} "
          f"{'Δ −12° [95%CI]':>28} "
          f"{'Δ −18° [95%CI]':>28}")
    print("  " + "-"*122)

    for var, label in variables_scalar.items():
        if var not in df_.columns:
            continue
        short = label.split('(')[0].strip()[:36]
        model = run_ols_scalar(df_, var)
        res   = extract_results(model, slopes_vs)

        cols_str = []
        for slope in slopes_vs:
            r = res.get(slope)
            if r is None:
                cols_str.append("                         n/a")
            else:
                cols_str.append(
                    f"{r['coef']:+.3f} "
                    f"[{r['ci_lo']:+.3f}, {r['ci_hi']:+.3f}]{r['sig']}"
                )
        print(f"  {short:<38} "
              f"{cols_str[0]:>28} "
              f"{cols_str[1]:>28} "
              f"{cols_str[2]:>28}")

    # --- Descriptive means per slope ---
    print(f"\n  Mean ± SD per slope (×BW or units)")
    print(f"  {'Variable':<38} {'0°':>10} {'−6°':>10} {'−12°':>10} {'−18°':>10}")
    print("  " + "-"*80)

    for var, label in variables_scalar.items():
        if var not in df_.columns:
            continue
        short   = label.split('(')[0].strip()[:36]
        row_str = []
        for slope in [0, -6, -12, -18]:
            vals = df_[df_['slope'] == slope][var].dropna()
            m = vals.mean() if len(vals) > 0 else np.nan
            s = vals.std()  if len(vals) > 0 else np.nan
            row_str.append(f"{m:.2f}±{s:.2f}")
        print(f"  {short:<38} "
              f"{row_str[0]:>10} {row_str[1]:>10} "
              f"{row_str[2]:>10} {row_str[3]:>10}")

    print(f"\n  * p < {alpha_bonferroni:.4f} (Bonferroni)")
    print("  Δ = estimated change vs. 0°, controlling for participant ID")

# ============================================================
# ALEXANDER 2016 REFERENCE
# ============================================================
print("\n\n" + "="*80)
print("REFERENCE — Alexander & Schwameder (2016)")
print("="*80)
print(f"\n  {'Variable':<38} {'0°':>10} {'−6°':>10} {'−12°':>10} {'−18°':>10}")
print("  " + "-"*80)
print(f"  {'[Table 1] Tibiofemoral mean':<38} "
      f"{'2.38':>10} {'2.32':>10} {'2.81':>10} {'3.04':>10}")
print(f"  {'[Table 1] Patellofemoral mean':<38} "
      f"{'0.23':>10} {'0.54':>10} {'1.36':>10} {'2.03':>10}")
print(f"  {'[Table 2] Tibiofemoral peak':<38} "
      f"{'4.09':>10} {'3.77':>10} {'4.88':>10} {'5.50':>10}")
print(f"  {'[Table 2] Patellofemoral peak':<38} "
      f"{'0.86':>10} {'1.46':>10} {'2.78':>10} {'3.96':>10}")
print("\n  Note: Alexander reports stance-phase mean (Table 1) and maximum (Table 2).")
print("  Your P1 values correspond best to Table 2 peaks.")
print("  Your P2 patellofemoral (0.215 ×BW at 0°) matches Alexander Table 1 (0.23 ×BW).")

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

# ============================================================
# Z-SCORE OUTLIER DETECTION — Peak 1
# ============================================================

variables_check = {
    'kneeFres':   'Tibiofemoral (×BW)',
    'knee_PFc':   'Patellofemoral (×BW)',
    'GRF_vert':   'GRF Vertical (×BW)',
    'angleKnee':  'Knee Angle (°)',
    'momentKnee': 'Knee Moment (Nm)',
    'speed':      'Speed (m/s)',
}

# Aggregate to 1 value per participant (mean across slopes and trials)
df_agg = (df_peak1.groupby('id')[list(variables_check.keys())]
          .mean()
          .reset_index())

# Compute z-scores
df_z = df_agg.copy()
for var in variables_check:
    df_z[f'z_{var}'] = stats.zscore(df_agg[var], nan_policy='omit')

# ============================================================
# PRINT Z-SCORE TABLE
# ============================================================
z_threshold = 2.0

print("="*95)
print(f"Z-SCORE TABLE — Peak 1  (|z| > {z_threshold} flagged with *)")
print("="*95)

# Header
header = f"  {'ID':<6}"
for var, label in variables_check.items():
    header += f" {label:>18}"
print(header)
print("  " + "-"*90)

flag_counts = {}
for _, row in df_z.iterrows():
    pid    = row['id']
    line   = f"  {pid:<6}"
    flags  = 0
    for var, label in variables_check.items():
        z = row[f'z_{var}']
        if np.isnan(z):
            line  += f" {'nan':>18}"
        elif abs(z) > z_threshold:
            line  += f" {z:>17.2f}*"
            flags += 1
        else:
            line  += f" {z:>18.2f}"
    flag_counts[pid] = flags
    marker = '  ⚠' if flags >= 2 else ''
    print(line + marker)

print("  " + "-"*90)
print(f"  * |z| > {z_threshold}  |  ⚠ = flagged on ≥2 variables")

# Summary
flagged = [pid for pid, n in flag_counts.items() if n >= 2]
print(f"\n  Participants flagged on ≥2 variables: "
      f"{flagged if flagged else 'None'}")

# ============================================================
# HEATMAP
# ============================================================
z_cols = [f'z_{var}' for var in variables_check]
z_matrix = df_z.set_index('id')[z_cols].values
ids      = df_z['id'].values
labels   = list(variables_check.values())

fig, ax = plt.subplots(figsize=(10, max(5, len(ids) * 0.4 + 1)))

im = ax.imshow(z_matrix, cmap='RdBu_r', vmin=-3, vmax=3,
               aspect='auto')

# Axes
ax.set_xticks(range(len(labels)))
ax.set_xticklabels(labels, rotation=30, ha='right', fontsize=9)
ax.set_yticks(range(len(ids)))
ax.set_yticklabels(ids, fontsize=9)

# Cell values
for i in range(len(ids)):
    for j in range(len(labels)):
        val  = z_matrix[i, j]
        mark = '*' if abs(val) > z_threshold else ''
        txt  = f"{val:.2f}{mark}" if not np.isnan(val) else 'nan'
        color = 'white' if abs(val) > 1.8 else 'black'
        ax.text(j, i, txt, ha='center', va='center',
                fontsize=8, color=color, fontweight='bold' if mark else 'normal')

plt.colorbar(im, ax=ax, label='Z-score', shrink=0.8)
ax.set_title('Z-score Heatmap — Peak 1\n'
             f'Red = high | Blue = low | * = |z| > {z_threshold}',
             fontsize=11, fontweight='bold', pad=12)

plt.tight_layout()
fig.savefig("figures/zscore_heatmap_peak1.png",
            dpi=300, bbox_inches='tight', facecolor='white')
print("\n✓ Saved: figures/zscore_heatmap_peak1.png")
plt.show()

In [ ]:
# ============================================================
# SENSITIVITY ANALYSIS — with vs without participant 20
# ============================================================

targets_check = ['kneeFres', 'knee_PFc', 'GRF_vert', 'angleKnee', 'momentKnee']
slopes_vs     = [-6, -12, -18]

def run_ols_scalar(df, outcome_col):
    df_clean = df[['id', 'slope', outcome_col]].dropna().copy()
    df_clean['slope'] = df_clean['slope'].astype(int)
    df_clean['id']    = df_clean['id'].astype(str)
    formula = f"{outcome_col} ~ C(slope, Treatment(0)) + C(id)"
    return smf.ols(formula, data=df_clean).fit()

def extract_coef(model, slopes_vs):
    results = {}
    for slope in slopes_vs:
        key = f"C(slope, Treatment(0))[T.{int(slope)}]"
        if key in model.params:
            results[slope] = {
                'coef': model.params[key],
                'p':    model.pvalues[key],
                'r2':   model.rsquared,
            }
    return results

df_full    = df_peak1.copy()
df_no20    = df_peak1[df_peak1['id'] != '20'].copy()

print("="*90)
print("SENSITIVITY ANALYSIS — Peak 1:  Full dataset vs. Excluding Participant 20")
print("="*90)

for var in targets_check:
    label = variables_check.get(var, var)

    m_full = run_ols_scalar(df_full, var)
    m_no20 = run_ols_scalar(df_no20, var)

    res_full = extract_coef(m_full, slopes_vs)
    res_no20 = extract_coef(m_no20, slopes_vs)

    print(f"\n  {label}")
    print(f"  {'':>6} {'R² full':>9} {'R² -P20':>9} {'ΔR²':>7}")
    print(f"  {'':>6} {m_full.rsquared:>9.3f} {m_no20.rsquared:>9.3f} "
          f"{m_no20.rsquared - m_full.rsquared:>+7.3f}")

    print(f"\n  {'Slope':>8} {'Δ full':>10} {'p full':>8} "
          f"{'Δ -P20':>10} {'p -P20':>8} {'Δ coef':>9}  {'Stable?'}")
    print("  " + "-"*72)

    for slope in slopes_vs:
        rf = res_full.get(slope, {})
        rn = res_no20.get(slope, {})
        if not rf or not rn:
            continue

        delta_coef = rn['coef'] - rf['coef']
        # Stable if: same direction, similar magnitude (< 20% change), same significance
        same_dir   = np.sign(rf['coef']) == np.sign(rn['coef'])
        pct_change = abs(delta_coef / rf['coef']) * 100 if rf['coef'] != 0 else np.nan
        both_sig   = (rf['p'] < 0.0167) == (rn['p'] < 0.0167)
        stable     = '✓ stable' if (same_dir and pct_change < 20 and both_sig) else '⚠ changes'

        print(f"  {slope:>8}° {rf['coef']:>+10.3f} {rf['p']:>8.4f} "
              f"{rn['coef']:>+10.3f} {rn['p']:>8.4f} "
              f"{delta_coef:>+9.3f}  {stable}  ({pct_change:.1f}% change)")

# Mean comparison
print("\n\n" + "="*90)
print("MEAN ± SD COMPARISON — 0° and −18°")
print("="*90)
print(f"\n  {'Variable':<30} {'Full 0°':>12} {'−P20 0°':>12} "
      f"{'Full −18°':>12} {'−P20 −18°':>12}")
print("  " + "-"*72)

for var in targets_check:
    label = variables_check.get(var, var)[:28]
    for slope, s_label in [(0, '0°'), (-18, '−18°')]:
        pass  # build below

    v_full_0   = df_full[df_full['slope']==0][var].dropna()
    v_no20_0   = df_no20[df_no20['slope']==0][var].dropna()
    v_full_18  = df_full[df_full['slope']==-18][var].dropna()
    v_no20_18  = df_no20[df_no20['slope']==-18][var].dropna()

    print(f"  {label:<30} "
          f"{v_full_0.mean():>5.2f}±{v_full_0.std():.2f} "
          f"{v_no20_0.mean():>5.2f}±{v_no20_0.std():.2f} "
          f"{v_full_18.mean():>5.2f}±{v_full_18.std():.2f} "
          f"{v_no20_18.mean():>5.2f}±{v_no20_18.std():.2f}")

print("\n  ✓ stable  = same direction, <20% coefficient change, same significance")
print("  ⚠ changes = direction flip, >20% change, or significance changes")

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import statsmodels.formula.api as smf

# ============================================================
# CONFIGURATION
# ============================================================
df_p1 = df_peak1[df_peak1['id'] != '20'].copy()
df_p1['id']    = df_p1['id'].astype(str).str.strip()
df_p1['slope'] = df_p1['slope'].astype(int)

model_config = {
    'kneeFres': {
        'features': ['angleKnee', 'angleHip',
                     'height', 'weight', 'speed', 'slope'],
        'label':    'Tibiofemoral Joint Compression Force (×BW)',
        'scenario': 'No Cadence & No Ankle Angle',
    },
    'knee_PFc': {
        'features': ['angleKnee', 'angleHip', 'angleAnkle',
                     'height', 'weight', 'speed', 'slope'],
        'label':    'Patellofemoral Joint Compression Force (×BW)',
        'scenario': 'No Cadence',
    },
}

slopes_ordered = [0, -6, -12, -18]
colors_slope   = {0: '#a8d5e2', -6: '#5b9fbf', -12: '#2a6a96', -18: '#0d2d55'}

# ============================================================
# FIT + PLOT
# ============================================================
results_summary = []

fig, axes = plt.subplots(1, 2, figsize=(16, 7))
fig.suptitle('Linear Regression — Peak 1 (Absorption Phase)\n'
             'Subject ID as Fixed Covariate | Participant 20 Excluded',
             fontsize=13, fontweight='bold')

for ax, (target, cfg) in zip(axes, model_config.items()):

    features = cfg['features']
    label    = cfg['label']

    # --- Clean data: avoid duplicate columns ---
    # slope is already in features, don't add it again
    all_cols = list(dict.fromkeys(['id', 'slope', target] + features))
    df_c     = df_p1[all_cols].dropna().copy().reset_index(drop=True)
    df_c['slope'] = df_c['slope'].astype(int)

    # --- Build X matrix ---
    subj_dummies = pd.get_dummies(df_c['id'], prefix='Subj', drop_first=True)
    X = pd.concat([df_c[features].reset_index(drop=True),
                   subj_dummies.reset_index(drop=True)], axis=1)
    y = df_c[target].values.astype(float)   # plain 1D numpy array

    # --- Fit ---
    model     = LinearRegression()
    model.fit(X.values, y)
    y_pred    = model.predict(X.values)     # plain 1D numpy array
    slope_arr = df_c['slope'].values.astype(int)  # plain 1D numpy array

    # quick sanity check
    assert y.ndim == 1, f"y is not 1D: {y.shape}"
    assert y_pred.ndim == 1, f"y_pred is not 1D: {y_pred.shape}"
    assert slope_arr.ndim == 1, f"slope_arr is not 1D: {slope_arr.shape}"

    # --- Stats ---
    r2       = r2_score(y, y_pred)
    rmse     = np.sqrt(mean_squared_error(y, y_pred))
    rmse_pct = (rmse / y.mean()) * 100
    n        = len(y)

    # --- Equation string ---
    eq_lines = [f"y = {model.intercept_:.2f}"]
    for name, coef in zip(X.columns, model.coef_):
        if 'Subj' not in name:
            clean = name.replace('angle', 'Ang')
            eq_lines.append(f"{coef:+.2f} × {clean}")
    eq_lines.append("[+ Subject Effects]")
    eq_str = "\n".join(eq_lines)

    results_summary.append({
        'Target':   target,
        'Scenario': cfg['scenario'],
        'n':        n,
        'R²':       round(r2, 3),
        'RMSE (%)': round(rmse_pct, 2),
        'Features': ", ".join(features),
    })

    # --- Scatter ---
    for slope in slopes_ordered:
        idx = np.where(slope_arr == slope)[0]  # explicit integer indices
        if len(idx) == 0:
            continue
        ax.scatter(y[idx], y_pred[idx],
                   color=colors_slope[slope], alpha=0.7, s=55,
                   label=f'{slope}°', edgecolors='white',
                   linewidths=0.4, zorder=3)

    # Perfect fit line
    vmin = min(y.min(), y_pred.min())
    vmax = max(y.max(), y_pred.max())
    pad  = (vmax - vmin) * 0.05
    ax.plot([vmin - pad, vmax + pad],
            [vmin - pad, vmax + pad],
            color='red', linestyle='--', linewidth=1.8,
            label='Perfect Fit', zorder=2)

    # Stats box
    stats_text = (f"n = {n}\n"
                  f"$R^2$ = {r2:.3f}\n"
                  f"RMSE = {rmse_pct:.1f}%\n\n"
                  f"{eq_str}")
    ax.text(0.03, 0.97, stats_text,
            transform=ax.transAxes, fontsize=7.5,
            verticalalignment='top',
            bbox=dict(boxstyle='round', facecolor='white',
                      alpha=0.9, edgecolor='#cccccc'))

    # Formatting
    ax.set_xlabel(f"Actual {label}", fontsize=10)
    ax.set_ylabel(f"Predicted {label}", fontsize=10)
    ax.set_title(f"Target: {label.split('(')[0].strip()}",
                 fontsize=11, fontweight='bold')
    ax.set_xlim(vmin - pad, vmax + pad)
    ax.set_ylim(vmin - pad, vmax + pad)
    ax.grid(True, linestyle=':', alpha=0.4)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.tick_params(labelsize=9)

    handles, lbls = ax.get_legend_handles_labels()
    ax.legend(handles, lbls, title='Slope (°)', fontsize=8,
              title_fontsize=8.5, loc='lower right',
              framealpha=0.9, edgecolor='#cccccc')

plt.tight_layout()
fig.savefig("figures/regression_peak1.png",
            dpi=300, bbox_inches='tight', facecolor='white')
print("✓ Saved: figures/regression_peak1.png")
plt.show()

# ============================================================
# SUMMARY TABLE
# ============================================================
print("\n" + "="*85)
print("REGRESSION SUMMARY — Peak 1  (Participant 20 excluded)")
print("="*85)
print(pd.DataFrame(results_summary).to_string(index=False))

# ============================================================
# COEFFICIENTS WITH p-VALUES (statsmodels)
# ============================================================
print("\n" + "="*85)
print("COEFFICIENTS WITH p-VALUES (statsmodels OLS)")
print("="*85)

for target, cfg in model_config.items():
    features = cfg['features']
    label    = cfg['label'].split('(')[0].strip()

    all_cols = list(dict.fromkeys(['id', 'slope', target] + features))
    df_c     = df_p1[all_cols].dropna().copy().reset_index(drop=True)
    df_c['slope'] = df_c['slope'].astype(int)
    df_c['id']    = df_c['id'].astype(str)

    formula  = f"{target} ~ " + " + ".join(features) + " + C(id)"
    sm_model = smf.ols(formula, data=df_c).fit()

    print(f"\n  [{label}]")
    print(f"  R² = {sm_model.rsquared:.3f}  |  "
          f"Adj. R² = {sm_model.rsquared_adj:.3f}  |  "
          f"n = {int(sm_model.nobs)}")
    print(f"\n  {'Variable':<20} {'Coef':>10} {'SE':>8} "
          f"{'t':>8} {'p':>10}  Sig")
    print("  " + "-"*65)

    for name in sm_model.params.index:
        if 'C(id)' in name:
            continue
        coef = sm_model.params[name]
        se   = sm_model.bse[name]
        t    = sm_model.tvalues[name]
        p    = sm_model.pvalues[name]
        sig  = ('***' if p < 0.001 else
                '**'  if p < 0.01  else
                '*'   if p < 0.05  else 'ns')
        clean = name.replace('angle', 'Ang')
        print(f"  {clean:<20} {coef:>10.3f} {se:>8.3f} "
              f"{t:>8.3f} {p:>10.4f}  {sig}")

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import statsmodels.formula.api as smf
from scipy import stats

# ============================================================
# STEP 1 — Z-SCORE CHECK PEAK 2
# ============================================================
variables_check = {
    'kneeFres':   'Tibiofemoral (×BW)',
    'knee_PFc':   'Patellofemoral (×BW)',
    'GRF_vert':   'GRF Vertical (×BW)',
    'angleKnee':  'Knee Angle (°)',
    'momentKnee': 'Knee Moment (Nm)',
    'speed':      'Speed (m/s)',
}

df_agg_p2 = (df_peak2.groupby('id')[list(variables_check.keys())]
             .mean().reset_index())

df_z2 = df_agg_p2.copy()
for var in variables_check:
    df_z2[f'z_{var}'] = stats.zscore(df_agg_p2[var], nan_policy='omit')

z_threshold = 2.0

print("="*95)
print(f"Z-SCORE TABLE — Peak 2  (|z| > {z_threshold} flagged with *)")
print("="*95)
header = f"  {'ID':<6}"
for label in variables_check.values():
    header += f" {label:>18}"
print(header)
print("  " + "-"*90)

flag_counts = {}
for _, row in df_z2.iterrows():
    pid   = row['id']
    line  = f"  {pid:<6}"
    flags = 0
    for var in variables_check:
        z = row[f'z_{var}']
        if np.isnan(z):
            line  += f" {'nan':>18}"
        elif abs(z) > z_threshold:
            line  += f" {z:>17.2f}*"
            flags += 1
        else:
            line  += f" {z:>18.2f}"
    flag_counts[pid] = flags
    marker = '  ⚠' if flags >= 2 else ''
    print(line + marker)

print("  " + "-"*90)
flagged_p2 = [pid for pid, n in flag_counts.items() if n >= 2]
print(f"\n  * |z| > {z_threshold}  |  ⚠ = flagged on ≥2 variables")
print(f"  Participants flagged on ≥2 variables: "
      f"{flagged_p2 if flagged_p2 else 'None'}")

# ============================================================
# STEP 2 — REGRESSION PEAK 2
# Same feature selection logic as Peak 1
# For Peak 2: tibiofemoral R²~0.67 so results will differ
# ============================================================

# Exclude participant 20 + any new outliers from Peak 2 z-score
exclude_p2 = list(set(['20'] + flagged_p2))
df_p2 = df_peak2[~df_peak2['id'].isin(exclude_p2)].copy()
df_p2['id']    = df_p2['id'].astype(str).str.strip()
df_p2['slope'] = df_p2['slope'].astype(int)

print(f"\n  Excluded from Peak 2 model: {exclude_p2}")
print(f"  Remaining participants: {df_p2['id'].nunique()}")

model_config_p2 = {
    'kneeFres': {
        'features': ['angleKnee', 'angleHip',
                     'height', 'weight', 'speed', 'slope'],
        'label':    'Tibiofemoral Joint Compression Force (×BW)',
        'scenario': 'No Cadence & No Ankle Angle',
    },
    'knee_PFc': {
        'features': ['angleKnee', 'angleHip', 'angleAnkle',
                     'height', 'weight', 'speed', 'slope'],
        'label':    'Patellofemoral Joint Compression Force (×BW)',
        'scenario': 'No Cadence',
    },
}

slopes_ordered = [0, -6, -12, -18]
colors_slope   = {0: '#a8d5e2', -6: '#5b9fbf', -12: '#2a6a96', -18: '#0d2d55'}

# ============================================================
# STEP 3 — FIT + PLOT
# ============================================================
results_summary_p2 = []

fig, axes = plt.subplots(1, 2, figsize=(16, 7))
fig.suptitle('Linear Regression — Peak 2 (Propulsion Phase)\n'
             f'Subject ID as Fixed Covariate | Excluded: {exclude_p2}',
             fontsize=13, fontweight='bold')

for ax, (target, cfg) in zip(axes, model_config_p2.items()):

    features = cfg['features']
    label    = cfg['label']

    # Clean data
    all_cols = list(dict.fromkeys(['id', 'slope', target] + features))
    df_c     = df_p2[all_cols].dropna().copy().reset_index(drop=True)
    df_c['slope'] = df_c['slope'].astype(int)

    # Build X
    subj_dummies = pd.get_dummies(df_c['id'], prefix='Subj', drop_first=True)
    X = pd.concat([df_c[features].reset_index(drop=True),
                   subj_dummies.reset_index(drop=True)], axis=1)
    y         = df_c[target].values.astype(float)
    slope_arr = df_c['slope'].values.astype(int)

    # Fit
    model  = LinearRegression()
    model.fit(X.values, y)
    y_pred = model.predict(X.values)

    # Stats
    r2       = r2_score(y, y_pred)
    rmse     = np.sqrt(mean_squared_error(y, y_pred))
    rmse_pct = (rmse / y.mean()) * 100
    n        = len(y)

    # Equation
    eq_lines = [f"y = {model.intercept_:.2f}"]
    for name, coef in zip(X.columns, model.coef_):
        if 'Subj' not in name:
            clean = name.replace('angle', 'Ang')
            eq_lines.append(f"{coef:+.2f} × {clean}")
    eq_lines.append("[+ Subject Effects]")
    eq_str = "\n".join(eq_lines)

    results_summary_p2.append({
        'Target':   target,
        'Scenario': cfg['scenario'],
        'n':        n,
        'R²':       round(r2, 3),
        'RMSE (%)': round(rmse_pct, 2),
        'Features': ", ".join(features),
    })

    # Scatter
    for slope in slopes_ordered:
        idx = np.where(slope_arr == slope)[0]
        if len(idx) == 0:
            continue
        edgecolor = '#666666' if slope == 0 else 'white'
        ax.scatter(y[idx], y_pred[idx],
                   color=colors_slope[slope], alpha=0.7, s=55,
                   label=f'{slope}°', edgecolors=edgecolor,
                   linewidths=0.6, zorder=3)

    # Perfect fit line
    vmin = min(y.min(), y_pred.min())
    vmax = max(y.max(), y_pred.max())
    pad  = (vmax - vmin) * 0.05
    ax.plot([vmin - pad, vmax + pad],
            [vmin - pad, vmax + pad],
            color='red', linestyle='--', linewidth=1.8,
            label='Perfect Fit', zorder=2)

    # Stats box
    stats_text = (f"n = {n}\n"
                  f"$R^2$ = {r2:.3f}\n"
                  f"RMSE = {rmse_pct:.1f}%\n\n"
                  f"{eq_str}")
    ax.text(0.03, 0.97, stats_text,
            transform=ax.transAxes, fontsize=7.5,
            verticalalignment='top',
            bbox=dict(boxstyle='round', facecolor='white',
                      alpha=0.9, edgecolor='#cccccc'))

    # Formatting
    ax.set_xlabel(f"Actual {label}", fontsize=10)
    ax.set_ylabel(f"Predicted {label}", fontsize=10)
    ax.set_title(f"Target: {label.split('(')[0].strip()}",
                 fontsize=11, fontweight='bold')
    ax.set_xlim(vmin - pad, vmax + pad)
    ax.set_ylim(vmin - pad, vmax + pad)
    ax.grid(True, linestyle=':', alpha=0.4)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.tick_params(labelsize=9)

    handles, lbls = ax.get_legend_handles_labels()
    ax.legend(handles, lbls, title='Slope (°)', fontsize=8,
              title_fontsize=8.5, loc='lower right',
              framealpha=0.9, edgecolor='#cccccc')

plt.tight_layout()
fig.savefig("figures/regression_peak2.png",
            dpi=300, bbox_inches='tight', facecolor='white')
print("\n✓ Saved: figures/regression_peak2.png")
plt.show()

# ============================================================
# STEP 4 — SUMMARY TABLE
# ============================================================
print("\n" + "="*85)
print("REGRESSION SUMMARY — Peak 2  (Propulsion Phase)")
print("="*85)
print(pd.DataFrame(results_summary_p2).to_string(index=False))

# ============================================================
# STEP 5 — COEFFICIENTS WITH p-VALUES
# ============================================================
print("\n" + "="*85)
print("COEFFICIENTS WITH p-VALUES (statsmodels OLS) — Peak 2")
print("="*85)

for target, cfg in model_config_p2.items():
    features = cfg['features']
    label    = cfg['label'].split('(')[0].strip()

    all_cols = list(dict.fromkeys(['id', 'slope', target] + features))
    df_c     = df_p2[all_cols].dropna().copy().reset_index(drop=True)
    df_c['slope'] = df_c['slope'].astype(int)
    df_c['id']    = df_c['id'].astype(str)

    formula  = f"{target} ~ " + " + ".join(features) + " + C(id)"
    sm_model = smf.ols(formula, data=df_c).fit()

    print(f"\n  [{label}]")
    print(f"  R² = {sm_model.rsquared:.3f}  |  "
          f"Adj. R² = {sm_model.rsquared_adj:.3f}  |  "
          f"n = {int(sm_model.nobs)}")
    print(f"\n  {'Variable':<20} {'Coef':>10} {'SE':>8} "
          f"{'t':>8} {'p':>10}  Sig")
    print("  " + "-"*65)

    for name in sm_model.params.index:
        if 'C(id)' in name:
            continue
        coef = sm_model.params[name]
        se   = sm_model.bse[name]
        t    = sm_model.tvalues[name]
        p    = sm_model.pvalues[name]
        sig  = ('***' if p < 0.001 else
                '**'  if p < 0.01  else
                '*'   if p < 0.05  else 'ns')
        clean = name.replace('angle', 'Ang')
        print(f"  {clean:<20} {coef:>10.3f} {se:>8.3f} "
              f"{t:>8.3f} {p:>10.4f}  {sig}")

# ============================================================
# STEP 6 — COMPARISON PEAK 1 vs PEAK 2
# ============================================================
print("\n\n" + "="*85)
print("COMPARISON — Peak 1 vs Peak 2")
print("="*85)
print(f"\n  {'Target':<15} {'Peak':<8} {'R²':>6} {'RMSE (%)':>10}  Notes")
print("  " + "-"*60)

p1_results = pd.DataFrame(results_summary)
p2_results = pd.DataFrame(results_summary_p2)

for target in ['kneeFres', 'knee_PFc']:
    r1 = p1_results[p1_results['Target'] == target].iloc[0]
    r2 = p2_results[p2_results['Target'] == target].iloc[0]
    note_p2 = ('⚠ lower fit' if r2['R²'] < 0.80
                else '✓ good fit')
    print(f"  {target:<15} {'Peak 1':<8} {r1['R²']:>6.3f} "
          f"{r1['RMSE (%)']:>9.1f}%  ✓ good fit")
    print(f"  {target:<15} {'Peak 2':<8} {r2['R²']:>6.3f} "
          f"{r2['RMSE (%)']:>9.1f}%  {note_p2}")
    print()

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import statsmodels.formula.api as smf
from scipy.interpolate import interp1d
from scipy import stats

# ============================================================
# STEP 1 — REBUILD df_peak2 WITH ADAPTIVE BANDS PER SLOPE
# ============================================================

# Adaptive propulsion bands per slope
# Level: P2 occurs earlier (~45–65%)
# Steeper downhill: P2 occurs later (~65–85%)
propulsion_bands = {
     0: (45, 65),
    -6: (50, 70),
   -12: (60, 80),
   -18: (65, 85),
}

stance_pct = np.linspace(0, 100, 101)

def interp_stance(arr, stance_fraction):
    arr = np.array(arr, dtype=float)
    n = len(arr)
    if n < 2:
        return np.full(101, np.nan)
    n_stance = max(2, round(stance_fraction * n))
    arr_s    = arr[:n_stance]
    x_orig   = np.linspace(0, 100, len(arr_s))
    f = interp1d(x_orig, arr_s, kind='linear',
                 bounds_error=False, fill_value=np.nan)
    return f(stance_pct)

def extract_peak_adaptive(arr, stance_fraction, slope):
    """Extract peak value using slope-specific propulsion band."""
    curve = interp_stance(arr, stance_fraction)
    band  = propulsion_bands.get(int(slope), (50, 85))
    mask  = (stance_pct >= band[0]) & (stance_pct <= band[1])
    seg   = curve[mask]
    if len(seg) == 0 or np.all(np.isnan(seg)):
        return np.nan
    return np.nanmax(seg)

# Variables to extract
ts_vars  = ['kneeFres', 'knee_PFc', 'GRF_vert', 'GRF_ap',
            'angleKnee', 'angleHip', 'angleAnkle',
            'momentKnee', 'momentHip', 'momentAnkle',
            'ankleFres', 'hipFres']
meta_cols = ['id', 'file', 'side', 'slope', 'condition',
             'height', 'weight', 'age', 'speed',
             'step_length', 'stride_length', 'gc_dur',
             'stance', 'cadence']

rows_p2 = []
for _, row in df_merged.iterrows():
    sf    = row['stance']
    slope = int(row['slope'])
    meta  = {col: row[col] for col in meta_cols if col in row.index}
    entry = meta.copy()
    for var in ts_vars:
        if var not in row.index:
            entry[var] = np.nan
            continue
        val = row[var]
        if not isinstance(val, (list, np.ndarray)) or len(val) < 2:
            entry[var] = np.nan
            continue
        # GRF_ap at P2 is positive (propulsion) → max
        entry[var] = extract_peak_adaptive(val, sf, slope)
    rows_p2.append(entry)

df_peak2_adaptive = pd.DataFrame(rows_p2)
df_peak2_adaptive['id']    = df_peak2_adaptive['id'].astype(str).str.strip()
df_peak2_adaptive['slope'] = df_peak2_adaptive['slope'].astype(int)

# Exclude participants 16, 26, 20
exclude = ['16', '26', '20']
df_peak2_adaptive = df_peak2_adaptive[
    ~df_peak2_adaptive['id'].isin(exclude)].copy()

# Normalize forces to ×BW
force_cols = ['kneeFres', 'knee_PFc', 'GRF_vert', 'GRF_ap',
              'ankleFres', 'hipFres']
for col in force_cols:
    if col in df_peak2_adaptive.columns:
        df_peak2_adaptive[col] = (df_peak2_adaptive[col] /
                                  (df_peak2_adaptive['weight'] * 9.81))

print("✓ df_peak2_adaptive built with adaptive propulsion bands")
print(f"  Rows         : {len(df_peak2_adaptive)}")
print(f"  Participants : {df_peak2_adaptive['id'].nunique()}")
print(f"  Slopes       : {sorted(df_peak2_adaptive['slope'].unique())}")
print(f"\n  Bands used per slope:")
for s, b in propulsion_bands.items():
    print(f"    {s:>4}° → {b[0]}–{b[1]}% stance")

print(f"\n  Sanity check — Mean ± SD at 0°:")
for var in ['kneeFres', 'knee_PFc', 'GRF_vert']:
    vals = df_peak2_adaptive[df_peak2_adaptive['slope']==0][var].dropna()
    print(f"    {var:<15}: {vals.mean():.3f} ± {vals.std():.3f} ×BW")

# ============================================================
# STEP 2 — Z-SCORE CHECK
# ============================================================
variables_check = {
    'kneeFres':   'Tibiofemoral (×BW)',
    'knee_PFc':   'Patellofemoral (×BW)',
    'GRF_vert':   'GRF Vertical (×BW)',
    'angleKnee':  'Knee Angle (°)',
    'momentKnee': 'Knee Moment (Nm)',
}

df_agg_p2 = (df_peak2_adaptive.groupby('id')[list(variables_check.keys())]
             .mean().reset_index())
df_z2 = df_agg_p2.copy()
for var in variables_check:
    df_z2[f'z_{var}'] = stats.zscore(df_agg_p2[var], nan_policy='omit')

z_threshold = 2.0
print("\n" + "="*85)
print(f"Z-SCORE TABLE — Peak 2 Adaptive  (|z| > {z_threshold} flagged *)")
print("="*85)
header = f"  {'ID':<6}"
for label in variables_check.values():
    header += f" {label:>20}"
print(header)
print("  " + "-"*85)

flag_counts = {}
for _, row in df_z2.iterrows():
    pid = row['id']
    line  = f"  {pid:<6}"
    flags = 0
    for var in variables_check:
        z = row[f'z_{var}']
        if np.isnan(z):
            line += f" {'nan':>20}"
        elif abs(z) > z_threshold:
            line += f" {z:>19.2f}*"
            flags += 1
        else:
            line += f" {z:>20.2f}"
    flag_counts[pid] = flags
    marker = '  ⚠' if flags >= 2 else ''
    print(line + marker)

print("  " + "-"*85)
flagged_p2 = [pid for pid, n in flag_counts.items() if n >= 2]
print(f"\n  Participants flagged ≥2 variables: "
      f"{flagged_p2 if flagged_p2 else 'None'}")

# ============================================================
# STEP 3 — REGRESSION
# ============================================================
exclude_final = list(set(exclude + flagged_p2))
df_p2 = df_peak2_adaptive[
    ~df_peak2_adaptive['id'].isin(exclude_final)].copy()
df_p2['id']    = df_p2['id'].astype(str).str.strip()
df_p2['slope'] = df_p2['slope'].astype(int)

print(f"\n  Final exclusions: {exclude_final}")
print(f"  Participants in model: {df_p2['id'].nunique()}")

model_config_p2 = {
    'kneeFres': {
        'features': ['angleKnee', 'angleHip',
                     'height', 'weight', 'speed', 'slope'],
        'label':    'Tibiofemoral Joint Compression Force (×BW)',
    },
    'knee_PFc': {
        'features': ['angleKnee', 'angleHip', 'angleAnkle',
                     'height', 'weight', 'speed', 'slope'],
        'label':    'Patellofemoral Joint Compression Force (×BW)',
    },
}

slopes_ordered = [0, -6, -12, -18]
colors_slope   = {0: '#a8d5e2', -6: '#5b9fbf', -12: '#2a6a96', -18: '#0d2d55'}

results_summary_p2 = []
fig, axes = plt.subplots(1, 2, figsize=(16, 7))
fig.suptitle('Linear Regression — Peak 2 (Propulsion Phase, Adaptive Bands)\n'
             f'Subject ID as Fixed Covariate | Excluded: {exclude_final}',
             fontsize=13, fontweight='bold')

for ax, (target, cfg) in zip(axes, model_config_p2.items()):
    features = cfg['features']
    label    = cfg['label']

    all_cols = list(dict.fromkeys(['id', 'slope', target] + features))
    df_c     = df_p2[all_cols].dropna().copy().reset_index(drop=True)
    df_c['slope'] = df_c['slope'].astype(int)

    subj_dummies = pd.get_dummies(df_c['id'], prefix='Subj', drop_first=True)
    X = pd.concat([df_c[features].reset_index(drop=True),
                   subj_dummies.reset_index(drop=True)], axis=1)
    y         = df_c[target].values.astype(float)
    slope_arr = df_c['slope'].values.astype(int)

    model  = LinearRegression()
    model.fit(X.values, y)
    y_pred = model.predict(X.values)

    r2       = r2_score(y, y_pred)
    rmse     = np.sqrt(mean_squared_error(y, y_pred))
    rmse_pct = (rmse / y.mean()) * 100
    n        = len(y)

    eq_lines = [f"y = {model.intercept_:.2f}"]
    for name, coef in zip(X.columns, model.coef_):
        if 'Subj' not in name:
            clean = name.replace('angle', 'Ang')
            eq_lines.append(f"{coef:+.2f} × {clean}")
    eq_lines.append("[+ Subject Effects]")
    eq_str = "\n".join(eq_lines)

    results_summary_p2.append({
        'Target':   target,
        'n':        n,
        'R²':       round(r2, 3),
        'RMSE (%)': round(rmse_pct, 2),
        'Features': ", ".join(features),
    })

    for slope in slopes_ordered:
        idx = np.where(slope_arr == slope)[0]
        if len(idx) == 0:
            continue
        ec = '#666666' if slope == 0 else 'white'
        ax.scatter(y[idx], y_pred[idx],
                   color=colors_slope[slope], alpha=0.7, s=55,
                   label=f'{slope}°', edgecolors=ec,
                   linewidths=0.6, zorder=3)

    vmin = min(y.min(), y_pred.min())
    vmax = max(y.max(), y_pred.max())
    pad  = (vmax - vmin) * 0.05
    ax.plot([vmin - pad, vmax + pad],
            [vmin - pad, vmax + pad],
            color='red', linestyle='--', linewidth=1.8,
            label='Perfect Fit', zorder=2)

    stats_text = (f"n = {n}\n$R^2$ = {r2:.3f}\nRMSE = {rmse_pct:.1f}%"
                  f"\n\n{eq_str}")
    ax.text(0.03, 0.97, stats_text, transform=ax.transAxes,
            fontsize=7.5, verticalalignment='top',
            bbox=dict(boxstyle='round', facecolor='white',
                      alpha=0.9, edgecolor='#cccccc'))

    ax.set_xlabel(f"Actual {label}", fontsize=10)
    ax.set_ylabel(f"Predicted {label}", fontsize=10)
    ax.set_title(f"Target: {label.split('(')[0].strip()}",
                 fontsize=11, fontweight='bold')
    ax.set_xlim(vmin - pad, vmax + pad)
    ax.set_ylim(vmin - pad, vmax + pad)
    ax.grid(True, linestyle=':', alpha=0.4)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.tick_params(labelsize=9)
    handles, lbls = ax.get_legend_handles_labels()
    ax.legend(handles, lbls, title='Slope (°)', fontsize=8,
              title_fontsize=8.5, loc='lower right',
              framealpha=0.9, edgecolor='#cccccc')

plt.tight_layout()
fig.savefig("figures/regression_peak2_adaptive.png",
            dpi=300, bbox_inches='tight', facecolor='white')
print("\n✓ Saved: figures/regression_peak2_adaptive.png")
plt.show()

# ============================================================
# STEP 4 — SUMMARY + COEFFICIENTS
# ============================================================
print("\n" + "="*85)
print("REGRESSION SUMMARY — Peak 2 Adaptive")
print("="*85)
print(pd.DataFrame(results_summary_p2).to_string(index=False))

print("\n" + "="*85)
print("COEFFICIENTS WITH p-VALUES — Peak 2 Adaptive")
print("="*85)

for target, cfg in model_config_p2.items():
    features = cfg['features']
    label    = cfg['label'].split('(')[0].strip()
    all_cols = list(dict.fromkeys(['id', 'slope', target] + features))
    df_c     = df_p2[all_cols].dropna().copy().reset_index(drop=True)
    df_c['slope'] = df_c['slope'].astype(int)
    df_c['id']    = df_c['id'].astype(str)
    formula  = f"{target} ~ " + " + ".join(features) + " + C(id)"
    sm_model = smf.ols(formula, data=df_c).fit()

    print(f"\n  [{label}]")
    print(f"  R² = {sm_model.rsquared:.3f} | "
          f"Adj. R² = {sm_model.rsquared_adj:.3f} | "
          f"n = {int(sm_model.nobs)}")
    print(f"\n  {'Variable':<20} {'Coef':>10} {'SE':>8} "
          f"{'t':>8} {'p':>10}  Sig")
    print("  " + "-"*65)
    for name in sm_model.params.index:
        if 'C(id)' in name:
            continue
        coef = sm_model.params[name]
        se   = sm_model.bse[name]
        t    = sm_model.tvalues[name]
        p    = sm_model.pvalues[name]
        sig  = ('***' if p < 0.001 else '**' if p < 0.01
                else '*' if p < 0.05 else 'ns')
        clean = name.replace('angle', 'Ang')
        print(f"  {clean:<20} {coef:>10.3f} {se:>8.3f} "
              f"{t:>8.3f} {p:>10.4f}  {sig}")

# ============================================================
# STEP 5 — PEAK 1 vs PEAK 2 COMPARISON
# ============================================================
print("\n\n" + "="*60)
print("COMPARISON — Peak 1 vs Peak 2")
print("="*60)
print(f"\n  {'Target':<15} {'Peak':<10} {'R²':>6} {'RMSE (%)':>10}")
print("  " + "-"*45)
for target in ['kneeFres', 'knee_PFc']:
    r1 = pd.DataFrame(results_summary)[
        pd.DataFrame(results_summary)['Target']==target].iloc[0]
    r2 = pd.DataFrame(results_summary_p2)[
        pd.DataFrame(results_summary_p2)['Target']==target].iloc[0]
    flag = '⚠' if r2['R²'] < 0.80 else '✓'
    print(f"  {target:<15} {'Peak 1':<10} {r1['R²']:>6.3f} "
          f"{r1['RMSE (%)']:>9.1f}%  ✓")
    print(f"  {target:<15} {'Peak 2':<10} {r2['R²']:>6.3f} "
          f"{r2['RMSE (%)']:>9.1f}%  {flag}")
    print()

In [ ]:
import json
import numpy as np
import pandas as pd

with open("MuscleJointForces_downhill.json", "r") as f:
    data = json.load(f)

print("Type:", type(data))
print("Total entries:", len(data))
print("\nFirst entry keys:", list(data[0].keys()))
print("\nFirst entry values (preview):")
for k, v in data[0].items():
    print(f"  {k}: {str(v)[:100]}")

In [ ]:
# ============================================================
# EXTRACT P1 AND P2 USING GRF_vert AS REFERENCE
# All other variables are extracted AT THE SAME TIME POINT
# ============================================================

stance_pct = np.linspace(0, 100, 101)

def interp_stance(arr, stance_fraction):
    arr = np.array(arr, dtype=float)
    n   = len(arr)
    if n < 2:
        return np.full(101, np.nan)
    n_stance = max(2, round(stance_fraction * n))
    arr_s    = arr[:n_stance]
    x_orig   = np.linspace(0, 100, len(arr_s))
    f = interp1d(x_orig, arr_s, kind='linear',
                 bounds_error=False, fill_value=np.nan)
    return f(stance_pct)


def find_grf_peaks(grf_curve):
    """
    Find P1 and P2 indices in a normalized GRF_vert curve.
    P1 = max in 5–40%
    Valley = min between P1 and 85%
    P2 = max between valley and 90%
    Returns (idx_p1, idx_p2) as indices into the 101-point array.
    """
    # P1
    m1   = (stance_pct >= 5) & (stance_pct <= 40)
    seg1 = grf_curve[m1]
    if np.all(np.isnan(seg1)):
        return None, None
    idx_p1_local = np.nanargmax(seg1)
    idx_p1       = np.where(m1)[0][idx_p1_local]
    pct_p1       = stance_pct[idx_p1]

    # Valley: min after P1 up to 80%
    m_v   = (stance_pct > pct_p1) & (stance_pct <= 80)
    seg_v = grf_curve[m_v]
    if np.all(np.isnan(seg_v)):
        return idx_p1, None
    idx_v_local = np.nanargmin(seg_v)
    idx_v       = np.where(m_v)[0][idx_v_local]
    pct_v       = stance_pct[idx_v]

    # P2: max after valley up to 90%
    m2   = (stance_pct > pct_v) & (stance_pct <= 90)
    seg2 = grf_curve[m2]
    if np.all(np.isnan(seg2)) or len(seg2) == 0:
        return idx_p1, None
    idx_p2_local = np.nanargmax(seg2)
    idx_p2       = np.where(m2)[0][idx_p2_local]

    return idx_p1, idx_p2


# Variables to extract (all time series)
ts_vars   = ['GRF_vert', 'GRF_ap', 'GRF_ml',
             'kneeFres', 'knee_PFc', 'ankleFres', 'hipFres',
             'angleKnee', 'angleHip', 'angleAnkle',
             'momentKnee', 'momentHip', 'momentAnkle']

meta_cols = ['id', 'file', 'side', 'slope', 'condition',
             'height', 'weight', 'age', 'speed',
             'step_length', 'stride_length', 'gc_dur',
             'stance', 'cadence']

rows_p1 = []
rows_p2 = []
skipped = 0

for _, row in df_merged.iterrows():
    sf   = row['stance']
    meta = {col: row[col] for col in meta_cols if col in row.index}

    # --- Get GRF_vert curve to find peak indices ---
    grf_raw = row.get('GRF_vert', None)
    if not isinstance(grf_raw, (list, np.ndarray)) or len(grf_raw) < 2:
        skipped += 1
        continue

    grf_curve = interp_stance(grf_raw, sf)
    idx_p1, idx_p2 = find_grf_peaks(grf_curve)

    if idx_p1 is None:
        skipped += 1
        continue

    entry_p1 = meta.copy()
    entry_p1['grf_pct_p1'] = stance_pct[idx_p1]

    entry_p2 = meta.copy()
    entry_p2['grf_pct_p2'] = stance_pct[idx_p2] if idx_p2 is not None else np.nan

    # --- Extract all variables AT the peak indices ---
    for var in ts_vars:
        raw = row.get(var, None)
        if not isinstance(raw, (list, np.ndarray)) or len(raw) < 2:
            entry_p1[var] = np.nan
            entry_p2[var] = np.nan
            continue

        curve = interp_stance(raw, sf)
        entry_p1[var] = curve[idx_p1] if idx_p1 is not None else np.nan
        entry_p2[var] = (curve[idx_p2] if idx_p2 is not None
                         else np.nan)

    rows_p1.append(entry_p1)
    rows_p2.append(entry_p2)

df_p1_final = pd.DataFrame(rows_p1)
df_p2_final = pd.DataFrame(rows_p2)

for df_ in [df_p1_final, df_p2_final]:
    df_['id']    = df_['id'].astype(str).str.strip()
    df_['slope'] = df_['slope'].astype(int)

# Exclude 16, 26, 20
exclude = ['16', '26', '20']
df_p1_final = df_p1_final[~df_p1_final['id'].isin(exclude)].copy()
df_p2_final = df_p2_final[~df_p2_final['id'].isin(exclude)].copy()

# Normalize forces to ×BW
force_cols = ['GRF_vert', 'GRF_ap', 'GRF_ml',
              'kneeFres', 'knee_PFc', 'ankleFres', 'hipFres']
for df_ in [df_p1_final, df_p2_final]:
    for col in force_cols:
        if col in df_.columns:
            df_[col] = df_[col] / (df_['weight'] * 9.81)

print("✓ GRF-based peak extraction complete")
print(f"  Skipped rows (no GRF data): {skipped}")
print(f"  P1 rows: {len(df_p1_final)} | "
      f"Participants: {df_p1_final['id'].nunique()}")
print(f"  P2 rows: {len(df_p2_final)} | "
      f"Participants: {df_p2_final['id'].nunique()}")

# --- Verify P2 timing ---
print(f"\n  Mean P2 timing (% stance) per slope:")
for slope in [0, -6, -12, -18]:
    v = df_p2_final[df_p2_final['slope']==slope]['grf_pct_p2'].dropna()
    print(f"    {slope:>4}°: {v.mean():.1f} ± {v.std():.1f}%  "
          f"(n={len(v)})")

# --- Sanity check values ---
print(f"\n  PEAK 1 sanity check (0°) — should match Alexander Table 2:")
for var, ref in [('kneeFres', '4.09'), ('knee_PFc', '0.86'),
                 ('GRF_vert', '~1.2')]:
    v = df_p1_final[df_p1_final['slope']==0][var].dropna()
    print(f"    {var:<15}: {v.mean():.3f} ± {v.std():.3f} ×BW  "
          f"(Alexander: {ref} ×BW)")

print(f"\n  PEAK 2 sanity check (0°) — should match Alexander Table 2:")
for var, ref in [('kneeFres', '4.09'), ('knee_PFc', '0.86'),
                 ('GRF_vert', '~1.2')]:
    v = df_p2_final[df_p2_final['slope']==0][var].dropna()
    print(f"    {var:<15}: {v.mean():.3f} ± {v.std():.3f} ×BW  "
          f"(Alexander: {ref} ×BW)")

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import statsmodels.formula.api as smf
from scipy import stats

# ============================================================
# Z-SCORE CHECK — PEAK 2
# ============================================================
variables_check = {
    'kneeFres':   'Tibiofemoral (×BW)',
    'knee_PFc':   'Patellofemoral (×BW)',
    'GRF_vert':   'GRF Vertical (×BW)',
    'angleKnee':  'Knee Angle (°)',
    'momentKnee': 'Knee Moment (Nm)',
}

df_agg_p2 = (df_p2_final.groupby('id')[list(variables_check.keys())]
             .mean().reset_index())
df_z2 = df_agg_p2.copy()
for var in variables_check:
    df_z2[f'z_{var}'] = stats.zscore(df_agg_p2[var], nan_policy='omit')

z_threshold = 2.0
print("="*88)
print(f"Z-SCORE TABLE — Peak 2  (|z| > {z_threshold} flagged *)")
print("="*88)
header = f"  {'ID':<6}"
for label in variables_check.values():
    header += f" {label:>18}"
print(header)
print("  " + "-"*88)

flag_counts = {}
for _, row in df_z2.iterrows():
    pid   = row['id']
    line  = f"  {pid:<6}"
    flags = 0
    for var in variables_check:
        z = row[f'z_{var}']
        if np.isnan(z):
            line  += f" {'nan':>18}"
        elif abs(z) > z_threshold:
            line  += f" {z:>17.2f}*"
            flags += 1
        else:
            line  += f" {z:>18.2f}"
    flag_counts[pid] = flags
    marker = '  ⚠' if flags >= 2 else ''
    print(line + marker)

print("  " + "-"*88)
flagged_p2 = [pid for pid, n in flag_counts.items() if n >= 2]
print(f"\n  Flagged ≥2 variables: {flagged_p2 if flagged_p2 else 'None'}")

# ============================================================
# REGRESSION — PEAK 2
# ============================================================
exclude_final = list(set(['16', '26', '20'] + flagged_p2))
df_p2 = df_p2_final[~df_p2_final['id'].isin(exclude_final)].copy()
df_p2['slope'] = df_p2['slope'].astype(int)

print(f"\n  Final exclusions: {exclude_final}")
print(f"  Participants in model: {df_p2['id'].nunique()}")

model_config_p2 = {
    'kneeFres': {
        'features': ['angleKnee', 'angleHip',
                     'height', 'weight', 'speed', 'slope'],
        'label':    'Tibiofemoral Joint Compression Force (×BW)',
    },
    'knee_PFc': {
        'features': ['angleKnee', 'angleHip', 'angleAnkle',
                     'height', 'weight', 'speed', 'slope'],
        'label':    'Patellofemoral Joint Compression Force (×BW)',
    },
}

slopes_ordered = [0, -6, -12, -18]
colors_slope   = {0: '#a8d5e2', -6: '#5b9fbf', -12: '#2a6a96', -18: '#0d2d55'}
results_p2     = []

fig, axes = plt.subplots(1, 2, figsize=(16, 7))
fig.suptitle('Linear Regression — Peak 2 (GRF-based extraction)\n'
             f'Subject ID as Fixed Covariate | Excluded: {exclude_final}',
             fontsize=13, fontweight='bold')

for ax, (target, cfg) in zip(axes, model_config_p2.items()):
    features = cfg['features']
    label    = cfg['label']

    all_cols = list(dict.fromkeys(['id', 'slope', target] + features))
    df_c     = df_p2[all_cols].dropna().copy().reset_index(drop=True)
    df_c['slope'] = df_c['slope'].astype(int)

    subj_dummies = pd.get_dummies(df_c['id'], prefix='Subj', drop_first=True)
    X = pd.concat([df_c[features].reset_index(drop=True),
                   subj_dummies.reset_index(drop=True)], axis=1)
    y         = df_c[target].values.astype(float)
    slope_arr = df_c['slope'].values.astype(int)

    model  = LinearRegression()
    model.fit(X.values, y)
    y_pred = model.predict(X.values)

    r2       = r2_score(y, y_pred)
    rmse     = np.sqrt(mean_squared_error(y, y_pred))
    rmse_pct = (rmse / y.mean()) * 100
    n        = len(y)

    eq_lines = [f"y = {model.intercept_:.2f}"]
    for name, coef in zip(X.columns, model.coef_):
        if 'Subj' not in name:
            eq_lines.append(
                f"{coef:+.2f} × {name.replace('angle','Ang')}")
    eq_lines.append("[+ Subject Effects]")

    results_p2.append({
        'Target':   target,
        'n':        n,
        'R²':       round(r2, 3),
        'RMSE (%)': round(rmse_pct, 2),
    })

    for slope in slopes_ordered:
        idx = np.where(slope_arr == slope)[0]
        if len(idx) == 0:
            continue
        ec = '#666666' if slope == 0 else 'white'
        ax.scatter(y[idx], y_pred[idx],
                   color=colors_slope[slope], alpha=0.7, s=55,
                   label=f'{slope}°', edgecolors=ec,
                   linewidths=0.6, zorder=3)

    vmin = min(y.min(), y_pred.min())
    vmax = max(y.max(), y_pred.max())
    pad  = (vmax - vmin) * 0.05
    ax.plot([vmin-pad, vmax+pad], [vmin-pad, vmax+pad],
            color='red', linestyle='--', linewidth=1.8,
            label='Perfect Fit', zorder=2)

    ax.text(0.03, 0.97,
            f"n = {n}\n$R^2$ = {r2:.3f}\nRMSE = {rmse_pct:.1f}%"
            f"\n\n{chr(10).join(eq_lines)}",
            transform=ax.transAxes, fontsize=7.5,
            verticalalignment='top',
            bbox=dict(boxstyle='round', facecolor='white',
                      alpha=0.9, edgecolor='#cccccc'))

    ax.set_xlabel(f"Actual {label}", fontsize=10)
    ax.set_ylabel(f"Predicted {label}", fontsize=10)
    ax.set_title(f"Target: {label.split('(')[0].strip()}",
                 fontsize=11, fontweight='bold')
    ax.set_xlim(vmin-pad, vmax+pad)
    ax.set_ylim(vmin-pad, vmax+pad)
    ax.grid(True, linestyle=':', alpha=0.4)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.tick_params(labelsize=9)
    handles, lbls = ax.get_legend_handles_labels()
    ax.legend(handles, lbls, title='Slope (°)', fontsize=8,
              title_fontsize=8.5, loc='lower right',
              framealpha=0.9, edgecolor='#cccccc')

plt.tight_layout()
fig.savefig("figures/regression_peak2_grf.png",
            dpi=300, bbox_inches='tight', facecolor='white')
print("\n✓ Saved: figures/regression_peak2_grf.png")
plt.show()

# ============================================================
# COEFFICIENTS WITH p-VALUES
# ============================================================
print("\n" + "="*70)
print("COEFFICIENTS WITH p-VALUES — Peak 2")
print("="*70)

for target, cfg in model_config_p2.items():
    features = cfg['features']
    label    = cfg['label'].split('(')[0].strip()
    all_cols = list(dict.fromkeys(['id', 'slope', target] + features))
    df_c     = df_p2[all_cols].dropna().copy().reset_index(drop=True)
    df_c['slope'] = df_c['slope'].astype(int)
    df_c['id']    = df_c['id'].astype(str)
    formula  = f"{target} ~ " + " + ".join(features) + " + C(id)"
    sm_model = smf.ols(formula, data=df_c).fit()

    print(f"\n  [{label}]")
    print(f"  R² = {sm_model.rsquared:.3f} | "
          f"Adj. R² = {sm_model.rsquared_adj:.3f} | "
          f"n = {int(sm_model.nobs)}")
    print(f"\n  {'Variable':<20} {'Coef':>10} {'SE':>8} "
          f"{'t':>8} {'p':>10}  Sig")
    print("  " + "-"*65)
    for name in sm_model.params.index:
        if 'C(id)' in name:
            continue
        coef = sm_model.params[name]
        se   = sm_model.bse[name]
        t    = sm_model.tvalues[name]
        p    = sm_model.pvalues[name]
        sig  = ('***' if p < 0.001 else '**' if p < 0.01
                else '*' if p < 0.05 else 'ns')
        print(f"  {name.replace('angle','Ang'):<20} "
              f"{coef:>10.3f} {se:>8.3f} "
              f"{t:>8.3f} {p:>10.4f}  {sig}")

# ============================================================
# FINAL COMPARISON P1 vs P2
# ============================================================
print("\n\n" + "="*60)
print("FINAL COMPARISON — Peak 1 vs Peak 2")
print("="*60)
print(f"\n  {'Target':<15} {'Peak':<10} {'R²':>6} {'RMSE (%)':>10}  Status")
print("  " + "-"*55)
p1_df = pd.DataFrame(results_summary)
p2_df = pd.DataFrame(results_p2)
for target in ['kneeFres', 'knee_PFc']:
    r1 = p1_df[p1_df['Target']==target].iloc[0]
    r2 = p2_df[p2_df['Target']==target].iloc[0]
    flag = '⚠ low R²' if r2['R²'] < 0.80 else '✓'
    print(f"  {target:<15} {'Peak 1':<10} {r1['R²']:>6.3f} "
          f"{r1['RMSE (%)']:>9.1f}%  ✓")
    print(f"  {target:<15} {'Peak 2':<10} {r2['R²']:>6.3f} "
          f"{r2['RMSE (%)']:>9.1f}%  {flag}")
    print()

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import statsmodels.formula.api as smf

# ============================================================
# REGRESSION — PEAK 2  (slopes -6, -12, -18 only)
# ============================================================

exclude_final = list(set(['16', '26', '20'] + flagged_p2))

# Exclude slope 0 for Peak 2
df_p2 = df_p2_final[
    (~df_p2_final['id'].isin(exclude_final)) &
    (df_p2_final['slope'] != 0)
].copy()
df_p2['slope'] = df_p2['slope'].astype(int)

print(f"  Excluded participants: {exclude_final}")
print(f"  Slopes included: {sorted(df_p2['slope'].unique())}")
print(f"  Participants: {df_p2['id'].nunique()}")
print(f"  Rows: {len(df_p2)}")

print(f"\n  Sanity check — means per slope:")
for slope in [-6, -12, -18]:
    df_s = df_p2[df_p2['slope']==slope]
    kf   = df_s['kneeFres'].mean()
    pf   = df_s['knee_PFc'].mean()
    print(f"    {slope:>4}°  kneeFres={kf:.3f} ×BW  "
          f"knee_PFc={pf:.3f} ×BW")

model_config_p2 = {
    'kneeFres': {
        'features': ['angleKnee', 'angleHip',
                     'height', 'weight', 'speed', 'slope'],
        'label':    'Tibiofemoral Joint Compression Force (×BW)',
    },
    'knee_PFc': {
        'features': ['angleKnee', 'angleHip', 'angleAnkle',
                     'height', 'weight', 'speed', 'slope'],
        'label':    'Patellofemoral Joint Compression Force (×BW)',
    },
}

slopes_ordered = [-6, -12, -18]   # no 0°
colors_slope   = {-6: '#5b9fbf', -12: '#2a6a96', -18: '#0d2d55'}
results_p2     = []

fig, axes = plt.subplots(1, 2, figsize=(16, 7))
fig.suptitle('Linear Regression — Peak 2 (Propulsion Phase)\n'
             'Downhill only (−6°, −12°, −18°) | '
             f'Subject ID as Fixed Covariate | Excluded: {exclude_final}',
             fontsize=13, fontweight='bold')

for ax, (target, cfg) in zip(axes, model_config_p2.items()):
    features = cfg['features']
    label    = cfg['label']

    all_cols = list(dict.fromkeys(['id', 'slope', target] + features))
    df_c     = df_p2[all_cols].dropna().copy().reset_index(drop=True)
    df_c['slope'] = df_c['slope'].astype(int)

    subj_dummies = pd.get_dummies(df_c['id'], prefix='Subj', drop_first=True)
    X = pd.concat([df_c[features].reset_index(drop=True),
                   subj_dummies.reset_index(drop=True)], axis=1)
    y         = df_c[target].values.astype(float)
    slope_arr = df_c['slope'].values.astype(int)

    model  = LinearRegression()
    model.fit(X.values, y)
    y_pred = model.predict(X.values)

    r2       = r2_score(y, y_pred)
    rmse     = np.sqrt(mean_squared_error(y, y_pred))
    rmse_pct = (rmse / y.mean()) * 100
    n        = len(y)

    eq_lines = [f"y = {model.intercept_:.2f}"]
    for name, coef in zip(X.columns, model.coef_):
        if 'Subj' not in name:
            eq_lines.append(
                f"{coef:+.2f} × {name.replace('angle','Ang')}")
    eq_lines.append("[+ Subject Effects]")

    results_p2.append({
        'Target':   target,
        'n':        n,
        'Slopes':   '−6°, −12°, −18°',
        'R²':       round(r2, 3),
        'RMSE (%)': round(rmse_pct, 2),
    })

    for slope in slopes_ordered:
        idx = np.where(slope_arr == slope)[0]
        if len(idx) == 0:
            continue
        ax.scatter(y[idx], y_pred[idx],
                   color=colors_slope[slope], alpha=0.7, s=55,
                   label=f'{slope}°', edgecolors='white',
                   linewidths=0.6, zorder=3)

    vmin = min(y.min(), y_pred.min())
    vmax = max(y.max(), y_pred.max())
    pad  = (vmax - vmin) * 0.05
    ax.plot([vmin-pad, vmax+pad], [vmin-pad, vmax+pad],
            color='red', linestyle='--', linewidth=1.8,
            label='Perfect Fit', zorder=2)

    ax.text(0.03, 0.97,
            f"n = {n}\n$R^2$ = {r2:.3f}\nRMSE = {rmse_pct:.1f}%"
            f"\n\n{chr(10).join(eq_lines)}",
            transform=ax.transAxes, fontsize=7.5,
            verticalalignment='top',
            bbox=dict(boxstyle='round', facecolor='white',
                      alpha=0.9, edgecolor='#cccccc'))

    ax.set_xlabel(f"Actual {label}", fontsize=10)
    ax.set_ylabel(f"Predicted {label}", fontsize=10)
    ax.set_title(f"Target: {label.split('(')[0].strip()}",
                 fontsize=11, fontweight='bold')
    ax.set_xlim(vmin-pad, vmax+pad)
    ax.set_ylim(vmin-pad, vmax+pad)
    ax.grid(True, linestyle=':', alpha=0.4)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.tick_params(labelsize=9)
    handles, lbls = ax.get_legend_handles_labels()
    ax.legend(handles, lbls, title='Slope (°)', fontsize=8,
              title_fontsize=8.5, loc='lower right',
              framealpha=0.9, edgecolor='#cccccc')

plt.tight_layout()
fig.savefig("figures/regression_peak2_downhill_only.png",
            dpi=300, bbox_inches='tight', facecolor='white')
print("\n✓ Saved: figures/regression_peak2_downhill_only.png")
plt.show()

# ============================================================
# COEFFICIENTS WITH p-VALUES
# ============================================================
print("\n" + "="*70)
print("COEFFICIENTS WITH p-VALUES — Peak 2 (−6°, −12°, −18°)")
print("="*70)

for target, cfg in model_config_p2.items():
    features = cfg['features']
    label    = cfg['label'].split('(')[0].strip()
    all_cols = list(dict.fromkeys(['id', 'slope', target] + features))
    df_c     = df_p2[all_cols].dropna().copy().reset_index(drop=True)
    df_c['slope'] = df_c['slope'].astype(int)
    df_c['id']    = df_c['id'].astype(str)
    formula  = f"{target} ~ " + " + ".join(features) + " + C(id)"
    sm_model = smf.ols(formula, data=df_c).fit()

    print(f"\n  [{label}]")
    print(f"  R² = {sm_model.rsquared:.3f} | "
          f"Adj. R² = {sm_model.rsquared_adj:.3f} | "
          f"n = {int(sm_model.nobs)}")
    print(f"\n  {'Variable':<20} {'Coef':>10} {'SE':>8} "
          f"{'t':>8} {'p':>10}  Sig")
    print("  " + "-"*65)
    for name in sm_model.params.index:
        if 'C(id)' in name:
            continue
        coef = sm_model.params[name]
        se   = sm_model.bse[name]
        t    = sm_model.tvalues[name]
        p    = sm_model.pvalues[name]
        sig  = ('***' if p < 0.001 else '**' if p < 0.01
                else '*' if p < 0.05 else 'ns')
        print(f"  {name.replace('angle','Ang'):<20} "
              f"{coef:>10.3f} {se:>8.3f} "
              f"{t:>8.3f} {p:>10.4f}  {sig}")

# ============================================================
# FINAL COMPARISON
# ============================================================
print("\n\n" + "="*65)
print("FINAL COMPARISON — Peak 1 (all slopes) vs Peak 2 (downhill only)")
print("="*65)
print(f"\n  {'Target':<15} {'Peak':<10} {'Slopes':<20} "
      f"{'R²':>6} {'RMSE (%)':>10}  Status")
print("  " + "-"*70)

p1_df = pd.DataFrame(results_summary)
p2_df = pd.DataFrame(results_p2)
for target in ['kneeFres', 'knee_PFc']:
    r1   = p1_df[p1_df['Target']==target].iloc[0]
    r2   = p2_df[p2_df['Target']==target].iloc[0]
    flag = '⚠ low R²' if r2['R²'] < 0.80 else '✓'
    print(f"  {target:<15} {'Peak 1':<10} {'0°,−6°,−12°,−18°':<20} "
          f"{r1['R²']:>6.3f} {r1['RMSE (%)']:>9.1f}%  ✓")
    print(f"  {target:<15} {'Peak 2':<10} {'−6°,−12°,−18°':<20} "
          f"{r2['R²']:>6.3f} {r2['RMSE (%)']:>9.1f}%  {flag}")
    print()

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import statsmodels.formula.api as smf

# ============================================================
# REGRESSION — PEAK 2
# Exclude: only participant 20
# Slopes: -6, -12, -18 (no level ground)
# ============================================================

df_p2 = df_p2_final[
    (df_p2_final['id'] != '20') &
    (df_p2_final['slope'] != 0)
].copy()
df_p2['id']    = df_p2['id'].astype(str).str.strip()
df_p2['slope'] = df_p2['slope'].astype(int)

print(f"  Excluded: ['20']")
print(f"  Slopes: {sorted(df_p2['slope'].unique())}")
print(f"  Participants: {df_p2['id'].nunique()} → {sorted(df_p2['id'].unique())}")
print(f"  Rows: {len(df_p2)}")

print(f"\n  Sanity check — means per slope (×BW):")
for slope in [-6, -12, -18]:
    df_s = df_p2[df_p2['slope']==slope]
    kf   = df_s['kneeFres'].mean()
    pf   = df_s['knee_PFc'].mean()
    grf  = df_s['GRF_vert'].mean()
    print(f"    {slope:>4}°  kneeFres={kf:.3f}  "
          f"knee_PFc={pf:.3f}  GRF={grf:.3f}")

model_config_p2 = {
    'kneeFres': {
        'features': ['angleKnee', 'angleHip',
                     'height', 'weight', 'speed', 'slope'],
        'label':    'Tibiofemoral Joint Compression Force (×BW)',
    },
    'knee_PFc': {
        'features': ['angleKnee', 'angleHip', 'angleAnkle',
                     'height', 'weight', 'speed', 'slope'],
        'label':    'Patellofemoral Joint Compression Force (×BW)',
    },
}

slopes_ordered = [-6, -12, -18]
colors_slope   = {-6: '#5b9fbf', -12: '#2a6a96', -18: '#0d2d55'}
results_p2     = []

fig, axes = plt.subplots(1, 2, figsize=(16, 7))
fig.suptitle('Linear Regression — Peak 2 (Propulsion Phase)\n'
             'Downhill only (−6°, −12°, −18°) | '
             'Subject ID as Fixed Covariate | Excluded: [20]',
             fontsize=13, fontweight='bold')

for ax, (target, cfg) in zip(axes, model_config_p2.items()):
    features = cfg['features']
    label    = cfg['label']

    all_cols = list(dict.fromkeys(['id', 'slope', target] + features))
    df_c     = df_p2[all_cols].dropna().copy().reset_index(drop=True)
    df_c['slope'] = df_c['slope'].astype(int)

    subj_dummies = pd.get_dummies(df_c['id'], prefix='Subj', drop_first=True)
    X = pd.concat([df_c[features].reset_index(drop=True),
                   subj_dummies.reset_index(drop=True)], axis=1)
    y         = df_c[target].values.astype(float)
    slope_arr = df_c['slope'].values.astype(int)

    model  = LinearRegression()
    model.fit(X.values, y)
    y_pred = model.predict(X.values)

    r2       = r2_score(y, y_pred)
    rmse     = np.sqrt(mean_squared_error(y, y_pred))
    rmse_pct = (rmse / y.mean()) * 100
    n        = len(y)

    eq_lines = [f"y = {model.intercept_:.2f}"]
    for name, coef in zip(X.columns, model.coef_):
        if 'Subj' not in name:
            eq_lines.append(
                f"{coef:+.2f} × {name.replace('angle','Ang')}")
    eq_lines.append("[+ Subject Effects]")

    results_p2.append({
        'Target':   target,
        'n':        n,
        'Excl':     '[20]',
        'R²':       round(r2, 3),
        'RMSE (%)': round(rmse_pct, 2),
    })

    for slope in slopes_ordered:
        idx = np.where(slope_arr == slope)[0]
        if len(idx) == 0:
            continue
        ax.scatter(y[idx], y_pred[idx],
                   color=colors_slope[slope], alpha=0.7, s=55,
                   label=f'{slope}°', edgecolors='white',
                   linewidths=0.6, zorder=3)

    vmin = min(y.min(), y_pred.min())
    vmax = max(y.max(), y_pred.max())
    pad  = (vmax - vmin) * 0.05
    ax.plot([vmin-pad, vmax+pad], [vmin-pad, vmax+pad],
            color='red', linestyle='--', linewidth=1.8,
            label='Perfect Fit', zorder=2)

    ax.text(0.03, 0.97,
            f"n = {n}\n$R^2$ = {r2:.3f}\nRMSE = {rmse_pct:.1f}%"
            f"\n\n{chr(10).join(eq_lines)}",
            transform=ax.transAxes, fontsize=7.5,
            verticalalignment='top',
            bbox=dict(boxstyle='round', facecolor='white',
                      alpha=0.9, edgecolor='#cccccc'))

    ax.set_xlabel(f"Actual {label}", fontsize=10)
    ax.set_ylabel(f"Predicted {label}", fontsize=10)
    ax.set_title(f"Target: {label.split('(')[0].strip()}",
                 fontsize=11, fontweight='bold')
    ax.set_xlim(vmin-pad, vmax+pad)
    ax.set_ylim(vmin-pad, vmax+pad)
    ax.grid(True, linestyle=':', alpha=0.4)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.tick_params(labelsize=9)
    handles, lbls = ax.get_legend_handles_labels()
    ax.legend(handles, lbls, title='Slope (°)', fontsize=8,
              title_fontsize=8.5, loc='lower right',
              framealpha=0.9, edgecolor='#cccccc')

plt.tight_layout()
fig.savefig("figures/regression_peak2_excl20only.png",
            dpi=300, bbox_inches='tight', facecolor='white')
print("\n✓ Saved: figures/regression_peak2_excl20only.png")
plt.show()

# ============================================================
# COEFFICIENTS WITH p-VALUES
# ============================================================
print("\n" + "="*70)
print("COEFFICIENTS WITH p-VALUES — Peak 2 (Excl: 20 only)")
print("="*70)

for target, cfg in model_config_p2.items():
    features = cfg['features']
    label    = cfg['label'].split('(')[0].strip()
    all_cols = list(dict.fromkeys(['id', 'slope', target] + features))
    df_c     = df_p2[all_cols].dropna().copy().reset_index(drop=True)
    df_c['slope'] = df_c['slope'].astype(int)
    df_c['id']    = df_c['id'].astype(str)
    formula  = f"{target} ~ " + " + ".join(features) + " + C(id)"
    sm_model = smf.ols(formula, data=df_c).fit()

    print(f"\n  [{label}]")
    print(f"  R² = {sm_model.rsquared:.3f} | "
          f"Adj. R² = {sm_model.rsquared_adj:.3f} | "
          f"n = {int(sm_model.nobs)}")
    print(f"\n  {'Variable':<20} {'Coef':>10} {'SE':>8} "
          f"{'t':>8} {'p':>10}  Sig")
    print("  " + "-"*65)
    for name in sm_model.params.index:
        if 'C(id)' in name:
            continue
        coef = sm_model.params[name]
        se   = sm_model.bse[name]
        t    = sm_model.tvalues[name]
        p    = sm_model.pvalues[name]
        sig  = ('***' if p < 0.001 else '**' if p < 0.01
                else '*' if p < 0.05 else 'ns')
        print(f"  {name.replace('angle','Ang'):<20} "
              f"{coef:>10.3f} {se:>8.3f} "
              f"{t:>8.3f} {p:>10.4f}  {sig}")

# ============================================================
# COMPARISON TABLE
# ============================================================
print("\n\n" + "="*75)
print("COMPARISON — Peak 1 vs Peak 2")
print("="*75)
print(f"\n  {'Target':<15} {'Peak':<8} {'Excl':<12} "
      f"{'Slopes':<22} {'R²':>6} {'RMSE (%)':>10}")
print("  " + "-"*75)

p1_df = pd.DataFrame(results_summary)
p2_df = pd.DataFrame(results_p2)

for target in ['kneeFres', 'knee_PFc']:
    r1 = p1_df[p1_df['Target']==target].iloc[0]
    r2 = p2_df[p2_df['Target']==target].iloc[0]
    flag = '  ⚠ low R²' if r2['R²'] < 0.80 else '  ✓'
    print(f"  {target:<15} {'Peak 1':<8} {'[20]':<12} "
          f"{'0°,−6°,−12°,−18°':<22} "
          f"{r1['R²']:>6.3f} {r1['RMSE (%)']:>9.1f}%  ✓")
    print(f"  {target:<15} {'Peak 2':<8} {'[20]':<12} "
          f"{'−6°,−12°,−18°':<22} "
          f"{r2['R²']:>6.3f} {r2['RMSE (%)']:>9.1f}%{flag}")
    print()

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import statsmodels.formula.api as smf

# ============================================================
# REGRESSION — PEAK 1
# Exclude: 16, 20, 26
# Slopes: 0, -6, -12, -18
# ============================================================

exclude_p1 = ['16', '20', '26']

df_p1 = df_p1_final[~df_p1_final['id'].isin(exclude_p1)].copy()
df_p1['id']    = df_p1['id'].astype(str).str.strip()
df_p1['slope'] = df_p1['slope'].astype(int)

print(f"  Excluded: {exclude_p1}")
print(f"  Slopes: {sorted(df_p1['slope'].unique())}")
print(f"  Participants: {df_p1['id'].nunique()} → {sorted(df_p1['id'].unique())}")
print(f"  Rows: {len(df_p1)}")

model_config_p1 = {
    'kneeFres': {
        'features': ['angleKnee', 'angleHip',
                     'height', 'weight', 'speed', 'slope'],
        'label':    'Tibiofemoral Joint Compression Force (×BW)',
        'scenario': 'No Cadence & No Ankle Angle',
    },
    'knee_PFc': {
        'features': ['angleKnee', 'angleHip', 'angleAnkle',
                     'height', 'weight', 'speed', 'slope'],
        'label':    'Patellofemoral Joint Compression Force (×BW)',
        'scenario': 'No Cadence',
    },
}

slopes_ordered = [0, -6, -12, -18]
colors_slope   = {0: '#a8d5e2', -6: '#5b9fbf', -12: '#2a6a96', -18: '#0d2d55'}
results_p1_new = []

fig, axes = plt.subplots(1, 2, figsize=(16, 7))
fig.suptitle('Linear Regression — Peak 1 (Absorption Phase)\n'
             f'Subject ID as Fixed Covariate | Excluded: {exclude_p1}',
             fontsize=13, fontweight='bold')

for ax, (target, cfg) in zip(axes, model_config_p1.items()):
    features = cfg['features']
    label    = cfg['label']

    all_cols = list(dict.fromkeys(['id', 'slope', target] + features))
    df_c     = df_p1[all_cols].dropna().copy().reset_index(drop=True)
    df_c['slope'] = df_c['slope'].astype(int)

    subj_dummies = pd.get_dummies(df_c['id'], prefix='Subj', drop_first=True)
    X = pd.concat([df_c[features].reset_index(drop=True),
                   subj_dummies.reset_index(drop=True)], axis=1)
    y         = df_c[target].values.astype(float)
    slope_arr = df_c['slope'].values.astype(int)

    model  = LinearRegression()
    model.fit(X.values, y)
    y_pred = model.predict(X.values)

    r2       = r2_score(y, y_pred)
    rmse     = np.sqrt(mean_squared_error(y, y_pred))
    rmse_pct = (rmse / y.mean()) * 100
    n        = len(y)

    eq_lines = [f"y = {model.intercept_:.2f}"]
    for name, coef in zip(X.columns, model.coef_):
        if 'Subj' not in name:
            eq_lines.append(
                f"{coef:+.2f} × {name.replace('angle','Ang')}")
    eq_lines.append("[+ Subject Effects]")

    results_p1_new.append({
        'Target':   target,
        'Scenario': cfg['scenario'],
        'n':        n,
        'Excl':     str(exclude_p1),
        'R²':       round(r2, 3),
        'RMSE (%)': round(rmse_pct, 2),
    })

    for slope in slopes_ordered:
        idx = np.where(slope_arr == slope)[0]
        if len(idx) == 0:
            continue
        ec = '#666666' if slope == 0 else 'white'
        ax.scatter(y[idx], y_pred[idx],
                   color=colors_slope[slope], alpha=0.7, s=55,
                   label=f'{slope}°', edgecolors=ec,
                   linewidths=0.6, zorder=3)

    vmin = min(y.min(), y_pred.min())
    vmax = max(y.max(), y_pred.max())
    pad  = (vmax - vmin) * 0.05
    ax.plot([vmin-pad, vmax+pad], [vmin-pad, vmax+pad],
            color='red', linestyle='--', linewidth=1.8,
            label='Perfect Fit', zorder=2)

    ax.text(0.03, 0.97,
            f"n = {n}\n$R^2$ = {r2:.3f}\nRMSE = {rmse_pct:.1f}%"
            f"\n\n{chr(10).join(eq_lines)}",
            transform=ax.transAxes, fontsize=7.5,
            verticalalignment='top',
            bbox=dict(boxstyle='round', facecolor='white',
                      alpha=0.9, edgecolor='#cccccc'))

    ax.set_xlabel(f"Actual {label}", fontsize=10)
    ax.set_ylabel(f"Predicted {label}", fontsize=10)
    ax.set_title(f"Target: {label.split('(')[0].strip()}",
                 fontsize=11, fontweight='bold')
    ax.set_xlim(vmin-pad, vmax+pad)
    ax.set_ylim(vmin-pad, vmax+pad)
    ax.grid(True, linestyle=':', alpha=0.4)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.tick_params(labelsize=9)
    handles, lbls = ax.get_legend_handles_labels()
    ax.legend(handles, lbls, title='Slope (°)', fontsize=8,
              title_fontsize=8.5, loc='lower right',
              framealpha=0.9, edgecolor='#cccccc')

plt.tight_layout()
fig.savefig("figures/regression_peak1_excl16_20_26.png",
            dpi=300, bbox_inches='tight', facecolor='white')
print("\n✓ Saved: figures/regression_peak1_excl16_20_26.png")
plt.show()

# ============================================================
# COEFFICIENTS WITH p-VALUES
# ============================================================
print("\n" + "="*70)
print(f"COEFFICIENTS WITH p-VALUES — Peak 1 (Excl: {exclude_p1})")
print("="*70)

for target, cfg in model_config_p1.items():
    features = cfg['features']
    label    = cfg['label'].split('(')[0].strip()
    all_cols = list(dict.fromkeys(['id', 'slope', target] + features))
    df_c     = df_p1[all_cols].dropna().copy().reset_index(drop=True)
    df_c['slope'] = df_c['slope'].astype(int)
    df_c['id']    = df_c['id'].astype(str)
    formula  = f"{target} ~ " + " + ".join(features) + " + C(id)"
    sm_model = smf.ols(formula, data=df_c).fit()

    print(f"\n  [{label}]")
    print(f"  R² = {sm_model.rsquared:.3f} | "
          f"Adj. R² = {sm_model.rsquared_adj:.3f} | "
          f"n = {int(sm_model.nobs)}")
    print(f"\n  {'Variable':<20} {'Coef':>10} {'SE':>8} "
          f"{'t':>8} {'p':>10}  Sig")
    print("  " + "-"*65)
    for name in sm_model.params.index:
        if 'C(id)' in name:
            continue
        coef = sm_model.params[name]
        se   = sm_model.bse[name]
        t    = sm_model.tvalues[name]
        p    = sm_model.pvalues[name]
        sig  = ('***' if p < 0.001 else '**' if p < 0.01
                else '*' if p < 0.05 else 'ns')
        print(f"  {name.replace('angle','Ang'):<20} "
              f"{coef:>10.3f} {se:>8.3f} "
              f"{t:>8.3f} {p:>10.4f}  {sig}")

# ============================================================
# COMPARISON: Peak 1 excl[20] vs Peak 1 excl[16,20,26]
# ============================================================
print("\n\n" + "="*75)
print("COMPARISON — Peak 1: excl[20] vs excl[16,20,26]")
print("="*75)
print(f"\n  {'Target':<15} {'Excluded':<18} {'n':>5} "
      f"{'R²':>6} {'RMSE (%)':>10}")
print("  " + "-"*60)

p1_old = pd.DataFrame(results_summary)   # excl [20] only
p1_new = pd.DataFrame(results_p1_new)    # excl [16,20,26]

for target in ['kneeFres', 'knee_PFc']:
    r_old = p1_old[p1_old['Target']==target].iloc[0]
    r_new = p1_new[p1_new['Target']==target].iloc[0]
    delta = r_new['R²'] - r_old['R²']
    print(f"  {target:<15} {'[20]':<18} {r_old['n']:>5} "
          f"{r_old['R²']:>6.3f} {r_old['RMSE (%)']:>9.1f}%")
    print(f"  {target:<15} {'[16,20,26]':<18} {r_new['n']:>5} "
          f"{r_new['R²']:>6.3f} {r_new['RMSE (%)']:>9.1f}%  "
          f"ΔR²={delta:+.3f}")
    print()

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d

# ============================================================
# COMPUTE TIME DELAY BETWEEN GRF PEAK AND knee_PFc PEAK
# For Peak 1 and Peak 2
# ============================================================

stance_pct = np.linspace(0, 100, 101)

def interp_stance(arr, stance_fraction):
    arr = np.array(arr, dtype=float)
    n   = len(arr)
    if n < 2:
        return np.full(101, np.nan)
    n_stance = max(2, round(stance_fraction * n))
    arr_s    = arr[:n_stance]
    x_orig   = np.linspace(0, 100, len(arr_s))
    f = interp1d(x_orig, arr_s, kind='linear',
                 bounds_error=False, fill_value=np.nan)
    return f(stance_pct)


def find_grf_peaks(grf_curve):
    """Returns (idx_p1, idx_p2) in the 101-point stance array."""
    # P1: max in 5–40%
    m1 = (stance_pct >= 5) & (stance_pct <= 40)
    s1 = grf_curve[m1]
    if np.all(np.isnan(s1)):
        return None, None
    idx_p1 = np.where(m1)[0][np.nanargmax(s1)]
    pct_p1 = stance_pct[idx_p1]

    # Valley: min after P1 up to 80%
    mv  = (stance_pct > pct_p1) & (stance_pct <= 80)
    sv  = grf_curve[mv]
    if np.all(np.isnan(sv)):
        return idx_p1, None
    idx_v   = np.where(mv)[0][np.nanargmin(sv)]
    pct_v   = stance_pct[idx_v]

    # P2: max after valley up to 90%
    m2 = (stance_pct > pct_v) & (stance_pct <= 90)
    s2 = grf_curve[m2]
    if np.all(np.isnan(s2)) or len(s2) == 0:
        return idx_p1, None
    idx_p2 = np.where(m2)[0][np.nanargmax(s2)]
    return idx_p1, idx_p2


def find_pfc_peak_near(pfc_curve, ref_pct, window=15):
    """Find PFc peak within ±window% of the reference GRF peak."""
    lo = max(0, ref_pct - window)
    hi = min(100, ref_pct + window)
    mask = (stance_pct >= lo) & (stance_pct <= hi)
    seg  = pfc_curve[mask]
    sp   = stance_pct[mask]
    if np.all(np.isnan(seg)) or len(seg) == 0:
        return np.nan
    return sp[np.nanargmax(seg)]


# --------------------------------------------------------
# Main loop: compute delays per trial
# --------------------------------------------------------
rows_delay = []
exclude = ['16', '20', '26']

for _, row in df_merged.iterrows():
    pid   = str(row['id']).strip()
    if pid in exclude:
        continue

    slope = int(row['slope'])
    sf    = row['stance']
    gc    = row['gc_dur']   # gait cycle duration in seconds

    grf_raw = row.get('GRF_vert', None)
    pfc_raw = row.get('knee_PFc', None)

    if (not isinstance(grf_raw, (list, np.ndarray)) or len(grf_raw) < 2 or
        not isinstance(pfc_raw, (list, np.ndarray)) or len(pfc_raw) < 2):
        continue

    grf_curve = interp_stance(grf_raw, sf)
    pfc_curve = interp_stance(pfc_raw, sf)

    idx_p1, idx_p2 = find_grf_peaks(grf_curve)

    if idx_p1 is None:
        continue

    # Stance duration in seconds = gc_dur * stance_fraction
    stance_dur = gc * sf   # seconds for full stance

    # --- Peak 1 ---
    grf_p1_pct = stance_pct[idx_p1]
    pfc_p1_pct = find_pfc_peak_near(pfc_curve, grf_p1_pct, window=15)
    if not np.isnan(pfc_p1_pct):
        # Convert % stance difference to seconds
        delay_p1_s = abs(pfc_p1_pct - grf_p1_pct) / 100 * stance_dur
        rows_delay.append({
            'id': pid, 'slope': slope, 'peak': 'Peak 1',
            'grf_pct': grf_p1_pct, 'pfc_pct': pfc_p1_pct,
            'delay_s': delay_p1_s,
        })

    # --- Peak 2 ---
    if idx_p2 is not None:
        grf_p2_pct = stance_pct[idx_p2]
        pfc_p2_pct = find_pfc_peak_near(pfc_curve, grf_p2_pct, window=15)
        if not np.isnan(pfc_p2_pct):
            delay_p2_s = abs(pfc_p2_pct - grf_p2_pct) / 100 * stance_dur
            rows_delay.append({
                'id': pid, 'slope': slope, 'peak': 'Peak 2',
                'grf_pct': grf_p2_pct, 'pfc_pct': pfc_p2_pct,
                'delay_s': delay_p2_s,
            })

df_delay = pd.DataFrame(rows_delay)

print(f"✓ Delay computed: {len(df_delay)} rows")
print(f"\n  Mean delay (s) per slope and peak:")
summary = (df_delay.groupby(['peak', 'slope'])['delay_s']
           .agg(['mean', 'std', 'count'])
           .round(4))
print(summary)

# ============================================================
# PLOT — one panel per peak, same figure
# ============================================================

slopes_ordered = [0, -6, -12, -18]
colors_slope   = {0: '#a8d5e2', -6: '#5b9fbf', -12: '#2a6a96', -18: '#0d2d55'}
slope_labels   = {0: '0°', -6: '−6°', -12: '−12°', -18: '−18°'}

fig, axes = plt.subplots(1, 2, figsize=(13, 5.5), sharey=False)
fig.suptitle('Absolute Time Delay between GRF Peak and PFc Peak\n'
             'by Slope and Phase | Excluded: [16, 20, 26]',
             fontsize=13, fontweight='bold')

for ax, peak_label in zip(axes, ['Peak 1', 'Peak 2']):

    df_pk = df_delay[df_delay['peak'] == peak_label]

    means = []
    stds  = []
    cols  = []
    xlbls = []

    for slope in slopes_ordered:
        # Peak 2 at slope 0 may be unreliable — skip if few data
        df_s = df_pk[df_pk['slope'] == slope]['delay_s'].dropna()
        if len(df_s) < 3:
            continue
        means.append(df_s.mean())
        stds.append(df_s.std())
        cols.append(colors_slope[slope])
        xlbls.append(slope_labels[slope])

    x = np.arange(len(xlbls))

    bars = ax.bar(x, means, yerr=stds,
                  color=cols, width=0.55,
                  error_kw=dict(ecolor='#444444', elinewidth=1.2,
                                capsize=5, capthick=1.2),
                  edgecolor='white', linewidth=0.5,
                  zorder=3)

    # Value labels on top of bars
    for bar, m, s in zip(bars, means, stds):
        ax.text(bar.get_x() + bar.get_width()/2,
                m + s + 0.0005,
                f'{m:.3f}s',
                ha='center', va='bottom',
                fontsize=8.5, color='#333333')

    ax.set_xticks(x)
    ax.set_xticklabels(xlbls, fontsize=10)
    ax.set_xlabel('Slope (°)', fontsize=11, labelpad=5)
    ax.set_ylabel('Absolute Time Delay (s)', fontsize=11, labelpad=5)
    ax.set_title(f'{peak_label}', fontsize=12, fontweight='bold')
    ax.set_ylim(0, max(means) + max(stds) * 2 + 0.005)
    ax.grid(True, axis='y', linestyle=':', alpha=0.4, color='#aaaaaa')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.tick_params(labelsize=9)

    # Annotation box
    ax.text(0.97, 0.97,
            'Tight synchronization\nbetween GRF and PFc peaks\njustifies GRF as temporal trigger',
            transform=ax.transAxes, ha='right', va='top',
            fontsize=7.5, style='italic', color='#2a6a96',
            bbox=dict(boxstyle='round,pad=0.5', facecolor='#e8f4f8',
                      edgecolor='#2a6a96', alpha=0.9))

plt.tight_layout()
fig.savefig("figures/time_delay_grf_pfc_p1_p2.png",
            dpi=300, bbox_inches='tight', facecolor='white')
print("\n✓ Saved: figures/time_delay_grf_pfc_p1_p2.png")
plt.show()

# ============================================================
# PRINT SUMMARY TABLE
# ============================================================
print("\n" + "="*65)
print("TIME DELAY SUMMARY — Mean ± SD (seconds)")
print("="*65)
print(f"\n  {'Peak':<10} {'Slope':>6} {'Mean (s)':>10} "
      f"{'SD (s)':>10} {'n':>5}")
print("  " + "-"*45)

for peak in ['Peak 1', 'Peak 2']:
    for slope in slopes_ordered:
        d = df_delay[(df_delay['peak']==peak) &
                     (df_delay['slope']==slope)]['delay_s'].dropna()
        if len(d) < 3:
            continue
        print(f"  {peak:<10} {slope:>6}°  "
              f"{d.mean():>10.4f}  {d.std():>10.4f}  {len(d):>5}")
    print()

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.lines as mlines
from scipy import stats

# ============================================================
# PREPARE DATA — both conditions, excl 16, 20, 26
# ============================================================

exclude = ['16', '20', '26']
slopes_ordered = [0, -6, -12, -18]
slope_labels   = {0: '0°', -6: '−6°', -12: '−12°', -18: '−18°'}

colors_slope = {
    0:   '#a8d5e2',
   -6:   '#5b9fbf',
  -12:   '#2a6a96',
  -18:   '#0d2d55',
}

color_cond = {
    'self-selected': '#2a6a96',
    'constant':      '#c0392b',
}

df_v = df_p1_final[~df_p1_final['id'].isin(exclude)].copy()
df_v['condition'] = df_v['condition'].str.lower().str.strip()
df_v['slope']     = df_v['slope'].astype(int)

print("Conditions:", df_v['condition'].unique())
print("Slopes    :", sorted(df_v['slope'].unique()))

# ============================================================
# FIGURE 1 — Speed by slope and condition
# Boxplot + individual points
# ============================================================

fig, ax = plt.subplots(figsize=(10, 5.5))

conditions = ['self-selected', 'constant']
n_slopes   = len(slopes_ordered)
width      = 0.35
x          = np.arange(n_slopes)

for ci, cond in enumerate(conditions):
    df_c   = df_v[df_v['condition'] == cond]
    means  = []
    stds   = []
    for slope in slopes_ordered:
        vals = df_c[df_c['slope'] == slope]['speed'].dropna()
        means.append(vals.mean())
        stds.append(vals.std())

    offset = (ci - 0.5) * width
    bars   = ax.bar(x + offset, means, width=width,
                    color=color_cond[cond], alpha=0.85,
                    label=cond.capitalize(),
                    edgecolor='white', linewidth=0.5, zorder=3)
    ax.errorbar(x + offset, means, yerr=stds,
                fmt='none', color='#333333',
                elinewidth=1.2, capsize=4, capthick=1.2, zorder=4)

    # Individual points
    for xi, slope in enumerate(slopes_ordered):
        vals = df_c[df_c['slope'] == slope]['speed'].dropna().values
        jitter = np.random.uniform(-0.06, 0.06, len(vals))
        ax.scatter(xi + offset + jitter, vals,
                   color=color_cond[cond], alpha=0.35,
                   s=20, zorder=5)

ax.set_xticks(x)
ax.set_xticklabels([slope_labels[s] for s in slopes_ordered], fontsize=11)
ax.set_xlabel('Slope (°)', fontsize=11, labelpad=5)
ax.set_ylabel('Walking Speed (m/s)', fontsize=11, labelpad=5)
ax.set_title('Walking Speed by Slope and Condition',
             fontsize=13, fontweight='bold', pad=12)
ax.legend(fontsize=10, framealpha=0.9, edgecolor='#cccccc')
ax.grid(True, axis='y', linestyle=':', alpha=0.4, color='#aaaaaa')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.tick_params(labelsize=9)

plt.tight_layout()
fig.savefig("figures/speed_by_slope_condition.png",
            dpi=300, bbox_inches='tight', facecolor='white')
print("✓ Saved: figures/speed_by_slope_condition.png")
plt.show()

# ============================================================
# STATS — is speed different between conditions per slope?
# ============================================================
print("\n" + "="*70)
print("SPEED COMPARISON — Self-selected vs Constant (paired t-test)")
print("="*70)
print(f"\n  {'Slope':>6}  {'Self-sel (m/s)':>16} {'Constant (m/s)':>16} "
      f"{'Δ':>8} {'p':>10}  Sig")
print("  " + "-"*65)

for slope in slopes_ordered:
    ss = df_v[(df_v['condition']=='self-selected') &
              (df_v['slope']==slope)]['speed'].dropna()
    ct = df_v[(df_v['condition']=='constant') &
              (df_v['slope']==slope)]['speed'].dropna()
    n  = min(len(ss), len(ct))
    if n < 3:
        continue
    t, p = stats.ttest_ind(ss, ct)
    delta = ss.mean() - ct.mean()
    sig   = ('***' if p < 0.001 else '**' if p < 0.01
             else '*' if p < 0.05 else 'ns')
    print(f"  {slope:>6}°  {ss.mean():>7.3f}±{ss.std():.3f}    "
          f"{ct.mean():>7.3f}±{ct.std():.3f}  "
          f"{delta:>+8.3f} {p:>10.4f}  {sig}")

# ============================================================
# FIGURE 2 — Speed vs kneeFres and knee_PFc
# Scatter colored by slope, split by condition
# ============================================================

fig, axes = plt.subplots(2, 2, figsize=(14, 11))
fig.suptitle('Walking Speed vs Joint Compression Force\n'
             'by Condition and Slope | Excluded: [16, 20, 26]',
             fontsize=13, fontweight='bold')

targets_plot = {
    'kneeFres': 'Tibiofemoral Contact Force (×BW)',
    'knee_PFc': 'Patellofemoral Contact Force (×BW)',
}

for row_idx, (target, ylabel) in enumerate(targets_plot.items()):
    for col_idx, cond in enumerate(conditions):
        ax   = axes[row_idx][col_idx]
        df_c = df_v[df_v['condition'] == cond]

        for slope in slopes_ordered:
            df_s = df_c[df_c['slope'] == slope]
            x_   = df_s['speed'].dropna()
            y_   = df_s[target].dropna()
            # align indices
            idx  = x_.index.intersection(y_.index)
            if len(idx) < 3:
                continue
            ax.scatter(x_[idx], y_[idx],
                       color=colors_slope[slope], alpha=0.6,
                       s=45, label=slope_labels[slope],
                       edgecolors='white', linewidths=0.4, zorder=3)

            # Regression line per slope
            xv = x_[idx].values
            yv = y_[idx].values
            if len(xv) > 2:
                m, b, r, p, _ = stats.linregress(xv, yv)
                xl = np.linspace(xv.min(), xv.max(), 50)
                ax.plot(xl, m*xl + b,
                        color=colors_slope[slope],
                        linewidth=1.5, alpha=0.8, zorder=4)

        # Overall regression (all slopes combined)
        x_all = df_c['speed'].dropna()
        y_all = df_c[target].dropna()
        idx_  = x_all.index.intersection(y_all.index)
        if len(idx_) > 5:
            m, b, r, p, _ = stats.linregress(
                x_all[idx_].values, y_all[idx_].values)
            xl = np.linspace(x_all[idx_].min(),
                             x_all[idx_].max(), 100)
            ax.plot(xl, m*xl + b, color='black',
                    linewidth=2, linestyle='--', zorder=5,
                    label=f'Overall (r={r:.2f})')
            ax.text(0.97, 0.05,
                    f'Overall: r={r:.2f}, p={p:.4f}',
                    transform=ax.transAxes, ha='right',
                    fontsize=8.5, color='black',
                    bbox=dict(boxstyle='round,pad=0.3',
                              facecolor='white',
                              edgecolor='#cccccc', alpha=0.9))

        ax.set_xlabel('Walking Speed (m/s)', fontsize=10)
        ax.set_ylabel(ylabel, fontsize=10)
        ax.set_title(f'{ylabel.split("(")[0].strip()}\n'
                     f'{cond.capitalize()}',
                     fontsize=10, fontweight='bold')
        ax.grid(True, linestyle=':', alpha=0.4, color='#aaaaaa')
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
        ax.tick_params(labelsize=8.5)

        # Slope legend only on first row, last column
        if row_idx == 0 and col_idx == 1:
            slope_handles = [
                mlines.Line2D([], [], color=colors_slope[s],
                              marker='o', markersize=6,
                              linestyle='-', linewidth=1.5,
                              label=slope_labels[s])
                for s in slopes_ordered
            ]
            ax.legend(handles=slope_handles, title='Slope',
                      fontsize=8.5, title_fontsize=8.5,
                      loc='upper left', framealpha=0.9,
                      edgecolor='#cccccc')

plt.tight_layout()
fig.savefig("figures/speed_vs_forces_by_condition.png",
            dpi=300, bbox_inches='tight', facecolor='white')
print("✓ Saved: figures/speed_vs_forces_by_condition.png")
plt.show()

# ============================================================
# FIGURE 3 — R² comparison: model per condition
# ============================================================

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

model_config = {
    'kneeFres': ['angleKnee', 'angleHip',
                 'height', 'weight', 'speed', 'slope'],
    'knee_PFc': ['angleKnee', 'angleHip', 'angleAnkle',
                 'height', 'weight', 'speed', 'slope'],
}

r2_results = []

for cond in conditions:
    df_c = df_v[df_v['condition'] == cond].copy()
    for target, features in model_config.items():
        all_cols = list(dict.fromkeys(
            ['id', 'slope', target] + features))
        df_c2 = df_c[all_cols].dropna().copy().reset_index(drop=True)
        df_c2['slope'] = df_c2['slope'].astype(int)

        subj_dummies = pd.get_dummies(df_c2['id'], prefix='Subj',
                                      drop_first=True)
        X = pd.concat([df_c2[features].reset_index(drop=True),
                       subj_dummies.reset_index(drop=True)], axis=1)
        y = df_c2[target].values.astype(float)

        mdl = LinearRegression()
        mdl.fit(X.values, y)
        y_pred = mdl.predict(X.values)
        r2  = r2_score(y, y_pred)
        rmse = np.sqrt(np.mean((y - y_pred)**2))
        rmse_pct = rmse / y.mean() * 100

        r2_results.append({
            'Condition': cond.capitalize(),
            'Target':    target,
            'n':         len(y),
            'R²':        round(r2, 3),
            'RMSE (%)':  round(rmse_pct, 2),
        })

df_r2 = pd.DataFrame(r2_results)

fig, axes = plt.subplots(1, 2, figsize=(11, 5))
fig.suptitle('Model Performance (R²) by Condition\n'
             'Peak 1 | Subject ID as Fixed Covariate',
             fontsize=13, fontweight='bold')

for ax, target in zip(axes, ['kneeFres', 'knee_PFc']):
    df_t  = df_r2[df_r2['Target'] == target]
    conds = df_t['Condition'].values
    r2s   = df_t['R²'].values
    rmses = df_t['RMSE (%)'].values
    cols  = [color_cond[c.lower()] for c in conds]
    x     = np.arange(len(conds))

    bars = ax.bar(x, r2s, color=cols, width=0.5,
                  edgecolor='white', linewidth=0.5,
                  alpha=0.85, zorder=3)

    for bar, r2, rmse, n in zip(
            bars, r2s, rmses,
            df_t['n'].values):
        ax.text(bar.get_x() + bar.get_width()/2,
                r2 + 0.003,
                f'R²={r2:.3f}\nRMSE={rmse:.1f}%\nn={n}',
                ha='center', va='bottom',
                fontsize=8.5, color='#333333')

    ax.set_xticks(x)
    ax.set_xticklabels(conds, fontsize=11)
    ax.set_ylabel('R²', fontsize=11)
    ax.set_ylim(0, 1.05)
    ax.set_title(
        ('Tibiofemoral' if target=='kneeFres'
         else 'Patellofemoral') + ' Contact Force',
        fontsize=11, fontweight='bold')
    ax.grid(True, axis='y', linestyle=':', alpha=0.4)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.axhline(0.80, color='red', linestyle='--',
               linewidth=1, alpha=0.6,
               label='R²=0.80 threshold')
    ax.legend(fontsize=8.5, framealpha=0.9)

plt.tight_layout()
fig.savefig("figures/r2_comparison_by_condition.png",
            dpi=300, bbox_inches='tight', facecolor='white')
print("✓ Saved: figures/r2_comparison_by_condition.png")
plt.show()

print("\n" + "="*60)
print("MODEL PERFORMANCE BY CONDITION")
print("="*60)
print(df_r2.to_string(index=False))

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import statsmodels.formula.api as smf

# ============================================================
# CONFIGURATION
# ============================================================
EXCLUDE_IDS = ['16', '20', '23']  # ← añadidos 16 y 23

df_p1 = df_peak1[~df_peak1['id'].astype(str).str.strip().isin(EXCLUDE_IDS)].copy()
df_p1['id']    = df_p1['id'].astype(str).str.strip()
df_p1['slope'] = df_p1['slope'].astype(int)

# ← CORRECTED per Feature Selection (rows 0 & 6 from the table)
model_config = {
    'kneeFres': {
        'features': ['angleKnee', 'angleHip', 'angleAnkle',   # ← angleAnkle added back
                     'height', 'weight', 'speed', 'slope'],   #   cadence excluded
        'label':    'Tibiofemoral Joint Compression Force',
        'scenario': 'No Cadence (Row 0)',
    },
    'knee_PFc': {
        'features': ['angleKnee', 'angleHip',                  # ← angleAnkle removed
                     'height', 'weight', 'speed', 'slope'],   #   cadence & ankle excluded
        'label':    'Patellofemoral Joint Compression Force',
        'scenario': 'No Cadence & No Ankle (Row 6)',
    },
}

slopes_ordered = [0, -6, -12, -18]
colors_slope   = {0: '#a8d5e2', -6: '#5b9fbf', -12: '#2a6a96', -18: '#0d2d55'}

# ============================================================
# FIT + PLOT
# ============================================================
results_summary = []

fig, axes = plt.subplots(1, 2, figsize=(16, 7))
fig.suptitle('Linear Regression — Peak 1 (Absorption Phase)\n'
             'Subject ID as Fixed Covariate | Participants 16, 20 & 23 Excluded',
             fontsize=13, fontweight='bold')

for ax, (target, cfg) in zip(axes, model_config.items()):

    features = cfg['features']
    label    = cfg['label']

    all_cols = list(dict.fromkeys(['id', 'slope', target] + features))
    df_c     = df_p1[all_cols].dropna().copy().reset_index(drop=True)
    df_c['slope'] = df_c['slope'].astype(int)

    # --- Build X matrix ---
    subj_dummies = pd.get_dummies(df_c['id'], prefix='Subj', drop_first=True)
    X = pd.concat([df_c[features].reset_index(drop=True),
                   subj_dummies.reset_index(drop=True)], axis=1)
    y          = df_c[target].values.astype(float)
    slope_arr  = df_c['slope'].values.astype(int)

    # --- Fit ---
    model  = LinearRegression()
    model.fit(X.values, y)
    y_pred = model.predict(X.values)

    # --- Stats ---
    r2       = r2_score(y, y_pred)
    rmse     = np.sqrt(mean_squared_error(y, y_pred))
    rmse_pct = (rmse / y.mean()) * 100
    n        = len(y)

    # --- Equation string ---
    eq_lines = [f"y = {model.intercept_:.2f}"]
    for name, coef in zip(X.columns, model.coef_):
        if 'Subj' not in name:
            clean = name.replace('angle', 'Ang')
            eq_lines.append(f"{coef:+.2f} × {clean}")
    eq_lines.append("[+ Subject Effects]")
    eq_str = "\n".join(eq_lines)

    results_summary.append({
        'Target':   target,
        'Scenario': cfg['scenario'],
        'n':        n,
        'R²':       round(r2, 3),
        'RMSE (%)': round(rmse_pct, 2),
        'Features': ", ".join(features),
    })

    # --- Scatter ---
    for slope in slopes_ordered:
        idx = np.where(slope_arr == slope)[0]
        if len(idx) == 0:
            continue
        ax.scatter(y[idx], y_pred[idx],
                   color=colors_slope[slope], alpha=0.7, s=55,
                   label=f'{slope}°', edgecolors='white',
                   linewidths=0.4, zorder=3)

    # Perfect fit line
    vmin = min(y.min(), y_pred.min())
    vmax = max(y.max(), y_pred.max())
    pad  = (vmax - vmin) * 0.05
    ax.plot([vmin - pad, vmax + pad],
            [vmin - pad, vmax + pad],
            color='red', linestyle='--', linewidth=1.8,
            label='Perfect Fit', zorder=2)

    # Stats box
    stats_text = (f"n = {n}\n"
                  f"$R^2$ = {r2:.3f}\n"
                  f"RMSE = {rmse_pct:.1f}%\n\n"
                  f"{eq_str}")
    ax.text(0.03, 0.97, stats_text,
            transform=ax.transAxes, fontsize=7.5,
            verticalalignment='top',
            bbox=dict(boxstyle='round', facecolor='white',
                      alpha=0.9, edgecolor='#cccccc'))

    ax.set_xlabel(f"Actual {label}", fontsize=10)
    ax.set_ylabel(f"Predicted {label}", fontsize=10)
    ax.set_title(f"Target: {label}", fontsize=11, fontweight='bold')
    ax.set_xlim(vmin - pad, vmax + pad)
    ax.set_ylim(vmin - pad, vmax + pad)
    ax.grid(True, linestyle=':', alpha=0.4)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.tick_params(labelsize=9)

    handles, lbls = ax.get_legend_handles_labels()
    ax.legend(handles, lbls, title='Slope (°)', fontsize=8,
              title_fontsize=8.5, loc='lower right',
              framealpha=0.9, edgecolor='#cccccc')

plt.tight_layout()
fig.savefig("figures/regression_peak1_final.png",
            dpi=300, bbox_inches='tight', facecolor='white')
plt.show()

# ============================================================
# SUMMARY TABLE
# ============================================================
print(pd.DataFrame(results_summary).to_string(index=False))

# ============================================================
# COEFFICIENTS WITH p-VALUES (statsmodels)
# ============================================================
for target, cfg in model_config.items():
    features = cfg['features']
    label    = cfg['label']

    all_cols = list(dict.fromkeys(['id', 'slope', target] + features))
    df_c     = df_p1[all_cols].dropna().copy().reset_index(drop=True)
    df_c['slope'] = df_c['slope'].astype(int)
    df_c['id']    = df_c['id'].astype(str)

    formula  = f"{target} ~ " + " + ".join(features) + " + C(id)"
    sm_model = smf.ols(formula, data=df_c).fit()

    print(f"\n[{label}]")
    print(f"R² = {sm_model.rsquared:.3f} | Adj. R² = {sm_model.rsquared_adj:.3f} | n = {int(sm_model.nobs)}")
    print(f"\n  {'Variable':<20} {'Coef':>10} {'SE':>8} {'t':>8} {'p':>10}  Sig")
    print("  " + "-"*65)

    for name in sm_model.params.index:
        if 'C(id)' in name:
            continue
        coef = sm_model.params[name]
        se   = sm_model.bse[name]
        t    = sm_model.tvalues[name]
        p    = sm_model.pvalues[name]
        sig  = ('***' if p < 0.001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns')
        clean = name.replace('angle', 'Ang')
        print(f"  {clean:<20} {coef:>10.3f} {se:>8.3f} {t:>8.3f} {p:>10.4f}  {sig}")